souffle: souffle::RamNestedOperation Class Reference
souffle::RamNestedOperation Class Reference
Abstract class for nesting operations.
#include <RamOperation.h>
Public Member Functions
void apply (const RamNodeMapper &map) override
Apply mapper.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of child nodes.
RamOperation & getOperation () const
Get nested operation.
void print (std::ostream &os, int tabpos) const override
Print.
RamNestedOperation (RamNodeType type, std::unique_ptr< RamOperation > nested)
Public Member Functions inherited from souffle::RamOperation
RamOperation * clone () const override=0
Create clone.
void print (std::ostream &os) const override
Pretty print.
RamOperation (RamNodeType type)
Public Member Functions inherited from souffle::RamNode
RamNodeType getNodeType () const
Get type of node.
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
RamNode (RamNodeType type)
virtual ~RamNode ()=default
A virtual destructor for RAM nodes.
Protected Member Functions
bool equal (const RamNode &node) const override
Check equality.
Private Attributes
std::unique_ptr< RamOperation > nestedOperation
Nested operation.
Detailed Description
Abstract class for nesting operations.
Definition at line 69 of file RamOperation.h.
Constructor & Destructor Documentation
souffle::RamNestedOperation::RamNestedOperation (RamNodeType type, std::unique_ptr< RamOperation > nested) inline
Definition at line 74 of file RamOperation.h.
             : RamOperation(type), nestedOperation(std::move(nested)) {}
Member Function Documentation
void souffle::RamNestedOperation::apply (const RamNodeMapper & map) inline override virtual
Apply mapper.
Implements souffle::RamOperation.
Reimplemented in souffle::RamFilter, souffle::RamAggregate, souffle::RamIndexScan, and souffle::RamRelationSearch.
Definition at line 94 of file RamOperation.h.
References nestedOperation.
Referenced by souffle::RamRelationSearch::apply(), souffle::RamAggregate::apply(), and souffle::RamFilter::apply().
{
         nestedOperation = map(std::move(nestedOperation));
     }
bool souffle::RamNestedOperation::equal (const RamNode & node) const inline override protected virtual
Check equality.
Implements souffle::RamOperation.
Reimplemented in souffle::RamFilter, souffle::RamAggregate, souffle::RamLookup, souffle::RamIndexScan, souffle::RamRelationSearch, and souffle::RamSearch.
Definition at line 100 of file RamOperation.h.
References getOperation().
Referenced by souffle::RamSearch::equal(), and souffle::RamFilter::equal().
{
         assert(nullptr != dynamic_cast<const RamNestedOperation*>(&node));
         const auto& other = static_cast<const RamNestedOperation&>(node);
         return getOperation() == other.getOperation();
     }
std::vector<const RamNode*> souffle::RamNestedOperation::getChildNodes () const inline override virtual
Obtain list of child nodes.
Implements souffle::RamOperation.
Reimplemented in souffle::RamFilter, souffle::RamAggregate, and souffle::RamIndexScan.
Definition at line 89 of file RamOperation.h.
References nestedOperation.
Referenced by souffle::RamIndexScan::getChildNodes(), and souffle::RamAggregate::getChildNodes().
{
         return {nestedOperation.get()};
     }
RamOperation& souffle::RamNestedOperation::getOperation () const inline
Get nested operation.
Definition at line 78 of file RamOperation.h.
References nestedOperation.
Referenced by souffle::RamScan::clone(), souffle::RamIndexScan::clone(), souffle::RamLookup::clone(), souffle::RamAggregate::clone(), souffle::RamFilter::clone(), souffle::Synthesiser::emitCode(), equal(), souffle::Interpreter::evalOp(), souffle::RamFilter::getChildNodes(), souffle::RamOperationDepthAnalysis::getDepth(), and souffle::CreateIndicesTransformer::rewriteScan().
{
         assert(nestedOperation);
         return *nestedOperation;
     }
void souffle::RamNestedOperation::print (std::ostream & os, int tabpos) const inline override virtual
Print.
Implements souffle::RamOperation.
Reimplemented in souffle::RamFilter, souffle::RamAggregate, souffle::RamLookup, souffle::RamIndexScan, and souffle::RamScan.
Definition at line 84 of file RamOperation.h.
References nestedOperation.
Referenced by souffle::RamScan::print(), souffle::RamIndexScan::print(), souffle::RamLookup::print(), souffle::RamAggregate::print(), and souffle::RamFilter::print().
{
         nestedOperation->print(os, tabpos + 1);
     }
Field Documentation
std::unique_ptr<RamOperation> souffle::RamNestedOperation::nestedOperation private
Nested operation.
Definition at line 71 of file RamOperation.h.
Referenced by apply(), getChildNodes(), getOperation(), and print().
The documentation for this class was generated from the following file:
RamOperation.h