souffle: souffle::CreateIndicesTransformer Class Reference
souffle::CreateIndicesTransformer Class Reference
#include <RamTransforms.h>
Public Member Functions
bool createIndices (RamProgram &program)
std::unique_ptr< RamValue > getIndexElement (RamCondition *c, size_t &element, size_t level)
Get indexable element.
std::string getName () const override
Get name of transformer.
std::unique_ptr< RamOperation > rewriteScan (const RamScan *scan)
Public Member Functions inherited from souffle::RamTransformer
bool apply (RamTranslationUnit &translationUnit)
Apply transformer.
virtual ~RamTransformer ()=default
Private Member Functions
bool transform (RamTranslationUnit &translationUnit) override
Transform RAM translation unit.
Private Attributes
RamConstValueAnalysis * rcva {nullptr}
RamValueLevelAnalysis * rvla {nullptr}
Detailed Description
Definition at line 54 of file RamTransforms.h.
Member Function Documentation
bool souffle::CreateIndicesTransformer::createIndices (RamProgram & program)
Parameters
program the program to be processed
Returns
whether the program was modified
Definition at line 244 of file RamTransforms.cpp.
References souffle::RamNode::apply(), and souffle::RamProgram::getMain().
Referenced by transform().
{
     // TODO: Change these to LambdaRamNodeMapper lambdas
     // Node-mapper that searches for and updates RAM scans nested in RAM inserts
     class RamScanCapturer : public RamNodeMapper {
         mutable bool modified = false;
         CreateIndicesTransformer* context;
     public:
         RamScanCapturer(CreateIndicesTransformer* c) : context(c) {}
         bool getModified() const {
             return modified;
         }
         std::unique_ptr<RamNode> operator()(std::unique_ptr<RamNode> node) const override {
             if (auto* scan = dynamic_cast<RamScan*>(node.get())) {
                 if (std::unique_ptr<RamOperation> op = context->rewriteScan(scan)) {
                     modified = true;
                     node = std::move(op);
                 }
             }
             node->apply(*this);
             return node;
         }
     };
     // Node-mapper that searches for and updates RAM inserts
     class RamInsertCapturer : public RamNodeMapper {
         mutable bool modified;
         CreateIndicesTransformer* context;
     public:
         RamInsertCapturer(CreateIndicesTransformer* c) : modified(false), context(c) {}
         bool getModified() const {
             return modified;
         }
         std::unique_ptr<RamNode> operator()(std::unique_ptr<RamNode> node) const override {
             // get all RAM inserts
             if (auto* insert = dynamic_cast<RamInsert*>(node.get())) {
                 RamScanCapturer scanUpdate(context);
                 insert->apply(scanUpdate);
                 if (!modified && scanUpdate.getModified()) {
                     modified = true;
                 }
             } else {
                 // no need to search for nested RAM inserts
                 node->apply(*this);
             }
             return node;
         }
     };
     // level all RAM inserts
     RamInsertCapturer insertUpdate(this);
     program.getMain()->apply(insertUpdate);
     return insertUpdate.getModified();
 }
std::unique_ptr< RamValue > souffle::CreateIndicesTransformer::getIndexElement (RamCondition * c, size_t & element, size_t level)
Get indexable element.
Definition at line 168 of file RamTransforms.cpp.
References souffle::EQ, souffle::RamValueLevelAnalysis::getLevel(), souffle::identifier(), souffle::RamConstValueAnalysis::isConstant(), lhs, rcva, rhs, and rvla.
Referenced by rewriteScan().
{
     if (auto* binRelOp = dynamic_cast<RamBinaryRelation*>(c)) {
         if (binRelOp->getOperator() == BinaryConstraintOp::EQ) {
             if (auto* lhs = dynamic_cast<RamElementAccess*>(binRelOp->getLHS())) {
                 RamValue* rhs = binRelOp->getRHS();
                 if (rvla->getLevel(lhs) == identifier &&
                         (rcva->isConstant(rhs) || rvla->getLevel(rhs) < identifier)) {
                     element = lhs->getElement();
                     return binRelOp->takeRHS();
                 }
             }
             if (auto* rhs = dynamic_cast<RamElementAccess*>(binRelOp->getRHS())) {
                 RamValue* lhs = binRelOp->getLHS();
                 if (rvla->getLevel(rhs) == identifier &&
                         (rcva->isConstant(lhs) || rvla->getLevel(lhs) < identifier)) {
                     element = rhs->getElement();
                     return binRelOp->takeLHS();
                 }
             }
         }
     }
     return nullptr;
 }
std::string souffle::CreateIndicesTransformer::getName () const inline override virtual
Get name of transformer.
Implements souffle::RamTransformer.
Definition at line 66 of file RamTransforms.h.
{
         return "CreateIndicesTransformer";
     }
std::unique_ptr< RamOperation > souffle::CreateIndicesTransformer::rewriteScan (const RamScan * scan)
Definition at line 193 of file RamTransforms.cpp.
References souffle::RamRelationReference::clone(), souffle::RamRelationReference::getArity(), souffle::RamSearch::getIdentifier(), getIndexElement(), souffle::RamNestedOperation::getOperation(), souffle::RamSearch::getProfileText(), souffle::RamRelationSearch::getRelation(), and souffle::identifier().
{
     if (const auto* filter = dynamic_cast<const RamFilter*>(&scan->getOperation())) {
         const RamRelationReference& rel = scan->getRelation();
         const size_t identifier = scan->getIdentifier();
         // Values of index per column of table (if indexable)
         std::vector<std::unique_ptr<RamValue>> queryPattern(rel.getArity());
         // Indexable columns for a range query
         SearchColumns keys = 0;
         // Remaining conditions which weren't handled by an index
         std::unique_ptr<RamCondition> condition;
         auto addCondition = [&](std::unique_ptr<RamCondition> c) {
             if (condition != nullptr) {
                 condition = std::make_unique<RamAnd>(std::move(condition), std::move(c));
             } else {
                 condition = std::move(c);
             }
         };
         for (RamCondition* cond : getConditions(filter->getCondition().clone())) {
             size_t element = 0;
             if (std::unique_ptr<RamValue> value = getIndexElement(cond, element, identifier)) {
                 keys |= (1 << element);
                 if (queryPattern[element] == nullptr) {
                     queryPattern[element] = std::move(value);
                 } else {
                     addCondition(std::unique_ptr<RamCondition>(cond));
                 }
             } else {
                 addCondition(std::unique_ptr<RamCondition>(cond));
             }
         }
         if (keys != 0) {
             // replace scan by index scan
             return std::make_unique<RamIndexScan>(std::unique_ptr<RamRelationReference>(rel.clone()),
                     identifier, std::move(queryPattern), keys,
                     condition == nullptr
                             ? std::unique_ptr<RamOperation>(filter->getOperation().clone())
                             : std::make_unique<RamFilter>(std::move(condition),
                                       std::unique_ptr<RamOperation>(filter->getOperation().clone())),
                     scan->getProfileText());
         }
     }
     return nullptr;
 }
bool souffle::CreateIndicesTransformer::transform (RamTranslationUnit & translationUnit) inline override private virtual
Transform RAM translation unit.
Implements souffle::RamTransformer.
Definition at line 59 of file RamTransforms.h.
References createIndices(), souffle::RamTranslationUnit::getAnalysis(), souffle::RamTranslationUnit::getProgram(), rcva, and rvla.
{
         rcva = translationUnit.getAnalysis<RamConstValueAnalysis>();
         rvla = translationUnit.getAnalysis<RamValueLevelAnalysis>();
         return createIndices(*translationUnit.getProgram());
     }
Field Documentation
RamConstValueAnalysis* souffle::CreateIndicesTransformer::rcva {nullptr} private
Definition at line 55 of file RamTransforms.h.
Referenced by getIndexElement(), and transform().
RamValueLevelAnalysis* souffle::CreateIndicesTransformer::rvla {nullptr} private
Definition at line 56 of file RamTransforms.h.
Referenced by getIndexElement(), and transform().
The documentation for this class was generated from the following files:
RamTransforms.h
RamTransforms.cpp