souffle: souffle::RamIntrinsicOperator Class Reference
souffle::RamIntrinsicOperator Class Reference
Operator that represents an intrinsic (built-in) functor.
#include <RamValue.h>
Public Member Functions
void apply (const RamNodeMapper &map) override
Apply mapper.
RamIntrinsicOperator * clone () const override
Create clone.
size_t getArgCount () const
const RamValue * getArgument (size_t i) const
std::vector< RamValue * > getArguments () const
Get values.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of child nodes.
FunctorOp getOperator () const
void print (std::ostream &os) const override
Print.
template<typename... Args>
RamIntrinsicOperator (FunctorOp op, Args...args)
RamIntrinsicOperator (FunctorOp op, std::vector< std::unique_ptr< RamValue >> args)
Public Member Functions inherited from souffle::RamValue
RamValue (RamNodeType type)
Public Member Functions inherited from souffle::RamNode
RamNodeType getNodeType () const
Get type of node.
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
RamNode (RamNodeType type)
virtual ~RamNode ()=default
A virtual destructor for RAM nodes.
Protected Member Functions
bool equal (const RamNode &node) const override
Check equality.
Private Attributes
std::vector< std::unique_ptr
< RamValue > > arguments
Arguments of the function.
FunctorOp operation
Operation symbol.
Detailed Description
Operator that represents an intrinsic (built-in) functor.
Definition at line 50 of file RamValue.h.
Constructor & Destructor Documentation
template<typename... Args> souffle::RamIntrinsicOperator::RamIntrinsicOperator (FunctorOp op, Args... args) inline
Definition at line 60 of file RamValue.h.
References arguments.
Referenced by clone().
                                                      : RamValue(RN_IntrinsicOperator), operation(op) {
         std::unique_ptr<RamValue> tmp[] = {std::move(args)...};
         for (auto& cur : tmp) {
             arguments.push_back(std::move(cur));
         }
     }
souffle::RamIntrinsicOperator::RamIntrinsicOperator (FunctorOp op, std::vector< std::unique_ptr< RamValue >> args) inline
Definition at line 67 of file RamValue.h.
             : RamValue(RN_IntrinsicOperator), operation(op), arguments(std::move(args)) {}
Member Function Documentation
void souffle::RamIntrinsicOperator::apply (const RamNodeMapper & map) inline override virtual
Apply mapper.
Implements souffle::RamNode.
Definition at line 121 of file RamValue.h.
References arguments.
{
         for (auto& arg : arguments) {
             arg = map(std::move(arg));
         }
     }
RamIntrinsicOperator* souffle::RamIntrinsicOperator::clone () const inline override virtual
Create clone.
Implements souffle::RamValue.
Definition at line 111 of file RamValue.h.
References arguments, operation, and RamIntrinsicOperator().
{
         std::vector<std::unique_ptr<RamValue>> argsCopy;
         for (auto& arg : arguments) {
             argsCopy.push_back(std::unique_ptr<RamValue>(arg->clone()));
         }
         auto res = new RamIntrinsicOperator(operation, std::move(argsCopy));
         return res;
     }
bool souffle::RamIntrinsicOperator::equal (const RamNode & node) const inline override protected virtual
Check equality.
Implements souffle::RamNode.
Definition at line 129 of file RamValue.h.
References arguments, souffle::equal_targets(), and getOperator().
{
         assert(nullptr != dynamic_cast<const RamIntrinsicOperator*>(&node));
         const auto& other = static_cast<const RamIntrinsicOperator&>(node);
         return getOperator() == other.getOperator() && equal_targets(arguments, other.arguments);
     }
size_t souffle::RamIntrinsicOperator::getArgCount () const inline
Definition at line 98 of file RamValue.h.
References arguments.
{
         return arguments.size();
     }
const RamValue* souffle::RamIntrinsicOperator::getArgument (size_t i) const inline
Definition at line 93 of file RamValue.h.
References arguments, and i.
Referenced by souffle::Synthesiser::emitCode().
{
         assert(i >= 0 && i < arguments.size() && "argument index out of bounds");
         return arguments[i].get();
     }
std::vector<RamValue*> souffle::RamIntrinsicOperator::getArguments () const inline
Get values.
Definition at line 89 of file RamValue.h.
References arguments, and souffle::toPtrVector().
Referenced by souffle::Interpreter::evalVal(), souffle::RamValueLevelAnalysis::getLevel(), souffle::getLevel(), souffle::isConstant(), and souffle::RamConstValueAnalysis::isConstant().
{
         return toPtrVector(arguments);
     }
std::vector<const RamNode*> souffle::RamIntrinsicOperator::getChildNodes () const inline override virtual
Obtain list of child nodes.
Implements souffle::RamNode.
Definition at line 103 of file RamValue.h.
References arguments.
{
         std::vector<const RamNode*> res;
         for (const auto& cur : arguments) {
             res.push_back(cur.get());
         }
         return res;
     }
FunctorOp souffle::RamIntrinsicOperator::getOperator () const inline
Definition at line 84 of file RamValue.h.
References operation.
Referenced by souffle::Synthesiser::emitCode(), equal(), and souffle::Interpreter::evalVal().
{
         return operation;
     }
void souffle::RamIntrinsicOperator::print (std::ostream & os) const inline override virtual
Print.
Implements souffle::RamNode.
Definition at line 71 of file RamValue.h.
References arguments, souffle::getSymbolForFunctorOp(), souffle::isInfixFunctorOp(), souffle::join(), and operation.
{
         if (isInfixFunctorOp(operation)) {
             os << "(";
             os << join(arguments, getSymbolForFunctorOp(operation), print_deref<std::unique_ptr<RamValue>>());
             os << ")";
         } else {
             os << getSymbolForFunctorOp(operation);
             os << "(";
             os << join(arguments, ",", print_deref<std::unique_ptr<RamValue>>());
             os << ")";
         }
     }
Field Documentation
std::vector<std::unique_ptr<RamValue> > souffle::RamIntrinsicOperator::arguments private
Arguments of the function.
Definition at line 56 of file RamValue.h.
Referenced by apply(), clone(), equal(), getArgCount(), getArgument(), getArguments(), getChildNodes(), print(), and RamIntrinsicOperator().
FunctorOp souffle::RamIntrinsicOperator::operation private
Operation symbol.
Definition at line 53 of file RamValue.h.
Referenced by clone(), getOperator(), and print().
The documentation for this class was generated from the following file:
RamValue.h