souffle: souffle::RamFilter Class Reference
souffle::RamFilter Class Reference
Filter statement.
#include <RamOperation.h>
Public Member Functions
void apply (const RamNodeMapper &map) override
Apply mapper.
RamFilter * clone () const override
Create clone.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of child nodes.
const RamCondition & getCondition () const
Get condition.
void print (std::ostream &os, int tabpos) const override
Print.
RamFilter (std::unique_ptr< RamCondition > cond, std::unique_ptr< RamOperation > nested)
Public Member Functions inherited from souffle::RamNestedOperation
RamOperation & getOperation () const
Get nested operation.
RamNestedOperation (RamNodeType type, std::unique_ptr< RamOperation > nested)
Public Member Functions inherited from souffle::RamOperation
void print (std::ostream &os) const override
Pretty print.
RamOperation (RamNodeType type)
Public Member Functions inherited from souffle::RamNode
RamNodeType getNodeType () const
Get type of node.
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
RamNode (RamNodeType type)
virtual ~RamNode ()=default
A virtual destructor for RAM nodes.
Protected Member Functions
bool equal (const RamNode &node) const override
Check equality.
Protected Attributes
std::unique_ptr< RamCondition > condition
Condition that is checked for each obtained tuple.
Detailed Description
Filter statement.
Definition at line 562 of file RamOperation.h.
Constructor & Destructor Documentation
souffle::RamFilter::RamFilter (std::unique_ptr< RamCondition > cond, std::unique_ptr< RamOperation > nested) inline
Definition at line 572 of file RamOperation.h.
Referenced by clone().
             : RamNestedOperation(RN_Filter, std::move(nested)), condition(std::move(cond)) {}
Member Function Documentation
void souffle::RamFilter::apply (const RamNodeMapper & map) inline override virtual
Apply mapper.
Reimplemented from souffle::RamNestedOperation.
Definition at line 601 of file RamOperation.h.
References souffle::RamNestedOperation::apply(), and condition.
{
         RamNestedOperation::apply(map);
         condition = map(std::move(condition));
     }
RamFilter* souffle::RamFilter::clone () const inline override virtual
Create clone.
Implements souffle::RamOperation.
Definition at line 595 of file RamOperation.h.
References souffle::RamOperation::clone(), condition, souffle::RamNestedOperation::getOperation(), and RamFilter().
{
         return new RamFilter(std::unique_ptr<RamCondition>(condition->clone()),
                 std::unique_ptr<RamOperation>(getOperation().clone()));
     }
bool souffle::RamFilter::equal (const RamNode & node) const inline override protected virtual
Check equality.
Reimplemented from souffle::RamNestedOperation.
Definition at line 608 of file RamOperation.h.
References souffle::RamNestedOperation::equal(), and getCondition().
{
         assert(nullptr != dynamic_cast<const RamFilter*>(&node));
         const auto& other = static_cast<const RamFilter&>(node);
         return getCondition() == other.getCondition() && RamNestedOperation::equal(node);
     }
std::vector<const RamNode*> souffle::RamFilter::getChildNodes () const inline override virtual
Obtain list of child nodes.
Reimplemented from souffle::RamNestedOperation.
Definition at line 590 of file RamOperation.h.
References condition, and souffle::RamNestedOperation::getOperation().
{
         return {condition.get(), &getOperation()};
     }
const RamCondition& souffle::RamFilter::getCondition () const inline
Get condition.
Definition at line 576 of file RamOperation.h.
References condition.
Referenced by souffle::Synthesiser::emitCode(), equal(), souffle::Interpreter::evalOp(), and print().
{
         return *condition;
     }
void souffle::RamFilter::print (std::ostream & os, int tabpos) const inline override virtual
Print.
Reimplemented from souffle::RamNestedOperation.
Definition at line 581 of file RamOperation.h.
References getCondition(), souffle::RamNestedOperation::print(), souffle::RamNode::print(), and souffle::times().
{
         os << times('\t', tabpos) << "IF ";
         getCondition().print(os);
         os << " {\n";
         RamNestedOperation::print(os, tabpos + 1);
         os << times('\t', tabpos) << "}\n";
     }
Field Documentation
std::unique_ptr<RamCondition> souffle::RamFilter::condition protected
Condition that is checked for each obtained tuple.
If condition is a nullptr, then no condition applies
Definition at line 569 of file RamOperation.h.
Referenced by apply(), clone(), getChildNodes(), and getCondition().
The documentation for this class was generated from the following file:
RamOperation.h