souffle: souffle::RamProvenanceExists Class Reference
souffle::RamProvenanceExists Class Reference
Existence check for a relation for provenance existence check.
#include <RamCondition.h>
Public Member Functions
void addArg (std::unique_ptr< RamValue > v)
Add argument.
void apply (const RamNodeMapper &map) override
Apply.
RamProvenanceExists * clone () const override
Create clone.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of child nodes.
SearchColumns getKey () const
Get key.
const RamRelationReference & getRelation () const
Get relation.
std::vector< RamValue * > getValues () const
Get arguments.
bool isTotal () const
Is key total.
void print (std::ostream &os) const override
Print.
RamProvenanceExists (std::unique_ptr< RamRelationReference > rel)
Public Member Functions inherited from souffle::RamCondition
RamCondition (RamNodeType type)
Public Member Functions inherited from souffle::RamNode
RamNodeType getNodeType () const
Get type of node.
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
RamNode (RamNodeType type)
virtual ~RamNode ()=default
A virtual destructor for RAM nodes.
Protected Member Functions
bool equal (const RamNode &node) const override
Check equality.
Protected Attributes
std::unique_ptr
< RamRelationReference > relation
std::vector< std::unique_ptr
< RamValue > > values
Pattern – nullptr if undefined.
Detailed Description
Existence check for a relation for provenance existence check.
Definition at line 351 of file RamCondition.h.
Constructor & Destructor Documentation
souffle::RamProvenanceExists::RamProvenanceExists (std::unique_ptr< RamRelationReference > rel) inline
Definition at line 361 of file RamCondition.h.
Referenced by clone().
             : RamCondition(RN_ProvenanceExists), relation(std::move(rel)) {}
Member Function Documentation
void souffle::RamProvenanceExists::addArg (std::unique_ptr< RamValue > v) inline
Add argument.
Definition at line 375 of file RamCondition.h.
References values.
{
         values.push_back(std::move(v));
     }
void souffle::RamProvenanceExists::apply (const RamNodeMapper & map) inline override virtual
Apply.
Implements souffle::RamNode.
Definition at line 439 of file RamCondition.h.
References relation, and values.
{
         relation = map(std::move(relation));
         for (auto& val : values) {
             if (val != nullptr) {
                 val = map(std::move(val));
             }
         }
     }
RamProvenanceExists* souffle::RamProvenanceExists::clone () const inline override virtual
Create clone.
Implements souffle::RamCondition.
Definition at line 425 of file RamCondition.h.
References souffle::RamValue::clone(), RamProvenanceExists(), relation, and values.
{
         RamProvenanceExists* res =
                 new RamProvenanceExists(std::unique_ptr<RamRelationReference>(relation->clone()));
         for (auto& cur : values) {
             RamValue* val = nullptr;
             if (cur != nullptr) {
                 val = cur->clone();
             }
             res->values.push_back(std::unique_ptr<RamValue>(val));
         }
         return res;
     }
bool souffle::RamProvenanceExists::equal (const RamNode & node) const inline override protected virtual
Check equality.
Implements souffle::RamNode.
Definition at line 450 of file RamCondition.h.
References souffle::equal_targets(), souffle::RamRelationReference::getRelation(), getRelation(), and values.
{
         assert(dynamic_cast<const RamProvenanceExists*>(&node));
         const auto& other = static_cast<const RamProvenanceExists&>(node);
         return getRelation() == other.getRelation() && equal_targets(values, other.values);
     }
std::vector<const RamNode*> souffle::RamProvenanceExists::getChildNodes () const inline override virtual
Obtain list of child nodes.
Implements souffle::RamNode.
Definition at line 416 of file RamCondition.h.
References relation, and values.
{
         std::vector<const RamNode*> res = {relation.get()};
         for (const auto& cur : values) {
             res.push_back(cur.get());
         }
         return res;
     }
SearchColumns souffle::RamProvenanceExists::getKey () const inline
Get key.
Definition at line 394 of file RamCondition.h.
References i, and values.
Referenced by souffle::Synthesiser::emitCode(), and souffle::Interpreter::evalCond().
{
         SearchColumns res = 0;
         // values.size() - 1 because we discard the height annotation
         for (unsigned i = 0; i < values.size() - 1; i++) {
             if (values[i]) {
                 res |= (1 << i);
             }
         }
         return res;
     }
const RamRelationReference& souffle::RamProvenanceExists::getRelation () const inline
Get relation.
Definition at line 365 of file RamCondition.h.
References relation.
Referenced by souffle::Synthesiser::emitCode(), equal(), and souffle::Interpreter::evalCond().
{
         return *relation;
     }
std::vector<RamValue*> souffle::RamProvenanceExists::getValues () const inline
Get arguments.
Definition at line 370 of file RamCondition.h.
References souffle::toPtrVector(), and values.
Referenced by souffle::Synthesiser::emitCode(), souffle::Interpreter::evalCond(), souffle::RamConditionLevelAnalysis::getLevel(), and souffle::getLevel().
{
         return toPtrVector(values);
     }
bool souffle::RamProvenanceExists::isTotal () const inline
Is key total.
Definition at line 406 of file RamCondition.h.
References values.
{
         for (const auto& cur : values) {
             if (!cur) {
                 return false;
             }
         }
         return true;
     }
void souffle::RamProvenanceExists::print (std::ostream & os) const inline override virtual
Print.
Implements souffle::RamNode.
Definition at line 380 of file RamCondition.h.
References souffle::join(), relation, and values.
{
         os << "("
            << join(values, ",",
                       [](std::ostream& out, const std::unique_ptr<RamValue>& value) {
                           if (!value) {
                               out << "_";
                           } else {
                               out << *value;
                           }
                       })
            << ") prov∉ " << relation->getName();
     }
Field Documentation
std::unique_ptr<RamRelationReference> souffle::RamProvenanceExists::relation protected
Definition at line 354 of file RamCondition.h.
Referenced by apply(), clone(), getChildNodes(), getRelation(), and print().
std::vector<std::unique_ptr<RamValue> > souffle::RamProvenanceExists::values protected
Pattern – nullptr if undefined.
Definition at line 358 of file RamCondition.h.
Referenced by addArg(), apply(), clone(), equal(), getChildNodes(), getKey(), getValues(), isTotal(), and print().
The documentation for this class was generated from the following file:
RamCondition.h