souffle: souffle::PiggyList< T > Class Template Reference
souffle::PiggyList< T > Class Template Reference
#include <PiggyList.h>
Data Structures
class iterator
Public Member Functions
size_t append (T element)
iterator begin ()
void clear ()
Clear all elements from the PiggyList.
size_t createNode ()
iterator end ()
T & get (size_t index) const
Retrieve a reference to the stored value at index.
T * getBlock (size_t blocknum) const
PiggyList & operator= (const PiggyList &other)=delete
copy assign ctor
PiggyList ()
PiggyList (size_t initialbitsize)
PiggyList (const PiggyList &other)
copy constructor
PiggyList (PiggyList &&other)=delete
move constructor
size_t size () const
Well, returns the number of nodes exist within the list + number of nodes queued to be inserted The reason for this, is that there may be many nodes queued up that haven't had time to had containers created and updated.
~PiggyList ()
Private Member Functions
void freeList ()
Free the arrays allocated within the linked list nodes.
Private Attributes
size_t allocsize = BLOCKSIZE
const size_t BLOCKBITS = 16ul
std::array< T *, max_conts > blockLookupTable = {}
const size_t BLOCKSIZE = (1ul << BLOCKBITS)
std::atomic< size_t > container_size
std::atomic< size_t > m_size
std::atomic< size_t > num_containers
SpinLock sl
Static Private Attributes
static constexpr size_t max_conts = 64
Detailed Description
template<class T>
class souffle::PiggyList< T >
Definition at line 126 of file PiggyList.h.
Constructor & Destructor Documentation
template<class T> souffle::PiggyList< T >::PiggyList () inline
Definition at line 156 of file PiggyList.h.
 : num_containers(0), container_size(0), m_size(0) {}
template<class T> souffle::PiggyList< T >::PiggyList (size_t initialbitsize) inline
Definition at line 157 of file PiggyList.h.
             : BLOCKBITS(initialbitsize), num_containers(0), container_size(0), m_size(0) {}
template<class T> souffle::PiggyList< T >::PiggyList (const PiggyList< T > & other) inline
copy constructor
Definition at line 161 of file PiggyList.h.
                                       : BLOCKBITS(other.BLOCKBITS) {
         num_containers.store(other.num_containers.load());
         container_size.store(other.container_size.load());
         m_size.store(other.m_size.load());
         // copy each chunk from other into this
         // the size of the next container to allocate
         size_t cSize = BLOCKSIZE;
         for (size_t i = 0; i < other.num_containers; ++i) {
             this->blockLookupTable[i] = new T[cSize];
             std::memcpy(this->blockLookupTable[i], other.blockLookupTable[i], cSize * sizeof(T));
             cSize <<= 1;
         }
         // if this isn't the case, uhh
         assert((cSize >> 1) == container_size.load());
     }
template<class T> souffle::PiggyList< T >::PiggyList (PiggyList< T > && other) delete
move constructor
template<class T> souffle::PiggyList< T >::~PiggyList () inline
Definition at line 182 of file PiggyList.h.
                  {
         freeList();
     }
Member Function Documentation
template<class T> size_t souffle::PiggyList< T >::append (T element) inline
Definition at line 200 of file PiggyList.h.
Referenced by souffle::EquivalenceRelation< tuple_type >::genAllDisjointSetLists().
{
         size_t new_index = m_size.fetch_add(1, std::memory_order_acquire);
         // will this not fit?
         if (container_size < new_index + 1) {
             sl.lock();
             // check and add as many containers as required
             while (container_size < new_index + 1) {
                 blockLookupTable[num_containers] = new T[allocsize];
                 num_containers += 1;
                 container_size += allocsize;
                 // double the number elements that will be allocated next time
                 allocsize <<= 1;
             }
             sl.unlock();
         }
         this->get(new_index) = element;
         return new_index;
     }
template<class T> iterator souffle::PiggyList< T >::begin () inline
Definition at line 306 of file PiggyList.h.
                      {
         return iterator(this);
     };
template<class T> void souffle::PiggyList< T >::clear () inline
Clear all elements from the PiggyList.
Definition at line 257 of file PiggyList.h.
Referenced by souffle::DisjointSet::clear().
                  {
         freeList();
         m_size = 0;
         num_containers = 0;
         allocsize = BLOCKSIZE;
         container_size = 0;
     }
template<class T> size_t souffle::PiggyList< T >::createNode () inline
Definition at line 221 of file PiggyList.h.
Referenced by souffle::DisjointSet::makeNode().
{
         size_t new_index = m_size.fetch_add(1, std::memory_order_acquire);
         // will this not fit?
         if (container_size < new_index + 1) {
             sl.lock();
             // check and add as many containers as required
             while (container_size < new_index + 1) {
                 blockLookupTable[num_containers] = new T[allocsize];
                 num_containers += 1;
                 container_size += allocsize;
                 // double the number elements that will be allocated next time
                 allocsize <<= 1;
             }
             sl.unlock();
         }
         return new_index;
     }
template<class T> iterator souffle::PiggyList< T >::end () inline
Definition at line 309 of file PiggyList.h.
                    {
         return iterator(this, size());
     };
template<class T> void souffle::PiggyList< T >::freeList () inline private
Free the arrays allocated within the linked list nodes.
Definition at line 146 of file PiggyList.h.
Referenced by souffle::PiggyList< std::atomic< block_t > >::clear(), and souffle::PiggyList< std::atomic< block_t > >::~PiggyList().
                     {
         sl.lock();
         // we don't know which ones are taken up!
         for (size_t i = 0; i < num_containers; ++i) {
             delete[] blockLookupTable[i];
         }
         sl.unlock();
     }
template<class T> T& souffle::PiggyList< T >::get (size_t index) const inline
Retrieve a reference to the stored value at index.
Parameters
index position to search
Returns
the value at index
Definition at line 246 of file PiggyList.h.
Referenced by souffle::DisjointSet::get(), souffle::EquivalenceRelation< tuple_type >::insertAll(), souffle::DisjointSet::makeNode(), souffle::PiggyList< T >::iterator::operator*(), souffle::EquivalenceRelation< TupleType >::iterator::updateAnterior(), and souffle::EquivalenceRelation< TupleType >::iterator::updatePosterior().
{
         // supa fast 2^16 size first block
         size_t nindex = index + BLOCKSIZE;
         size_t blockNum = (63 - __builtin_clzll(nindex));
         size_t blockInd = (nindex) & ((1 << blockNum) - 1);
         return this->getBlock(blockNum - BLOCKBITS)[blockInd];
     }
template<class T> T* souffle::PiggyList< T >::getBlock (size_t blocknum) const inline
Definition at line 196 of file PiggyList.h.
Referenced by souffle::PiggyList< std::atomic< block_t > >::get().
{
         return this->blockLookupTable[blocknum];
     }
template<class T> PiggyList& souffle::PiggyList< T >::operator= (const PiggyList< T > & other) delete
copy assign ctor
template<class T> size_t souffle::PiggyList< T >::size () const inline
Well, returns the number of nodes exist within the list + number of nodes queued to be inserted The reason for this, is that there may be many nodes queued up that haven't had time to had containers created and updated.
Returns
the number of nodes exist within the list + number of nodes queued to be inserted
Definition at line 192 of file PiggyList.h.
Referenced by souffle::PiggyList< std::atomic< block_t > >::end(), souffle::EquivalenceRelation< tuple_type >::genAllDisjointSetLists(), souffle::EquivalenceRelation< tuple_type >::insertAll(), souffle::EquivalenceRelation< TupleType >::iterator::iterator(), souffle::EquivalenceRelation< TupleType >::iterator::operator++(), and souffle::DisjointSet::size().
{
         return m_size.load();
     };
Field Documentation
template<class T> size_t souffle::PiggyList< T >::allocsize = BLOCKSIZE private
Definition at line 132 of file PiggyList.h.
Referenced by souffle::PiggyList< std::atomic< block_t > >::append(), souffle::PiggyList< std::atomic< block_t > >::clear(), and souffle::PiggyList< std::atomic< block_t > >::createNode().
template<class T> const size_t souffle::PiggyList< T >::BLOCKBITS = 16ul private
Definition at line 127 of file PiggyList.h.
Referenced by souffle::PiggyList< std::atomic< block_t > >::get().
template<class T> std::array<T*, max_conts> souffle::PiggyList< T >::blockLookupTable = {} private
Definition at line 138 of file PiggyList.h.
Referenced by souffle::PiggyList< std::atomic< block_t > >::append(), souffle::PiggyList< std::atomic< block_t > >::createNode(), souffle::PiggyList< std::atomic< block_t > >::freeList(), souffle::PiggyList< std::atomic< block_t > >::getBlock(), and souffle::PiggyList< std::atomic< block_t > >::PiggyList().
template<class T> const size_t souffle::PiggyList< T >::BLOCKSIZE = (1ul << BLOCKBITS) private
Definition at line 128 of file PiggyList.h.
Referenced by souffle::PiggyList< std::atomic< block_t > >::clear(), souffle::PiggyList< std::atomic< block_t > >::get(), and souffle::PiggyList< std::atomic< block_t > >::PiggyList().
template<class T> std::atomic<size_t> souffle::PiggyList< T >::container_size private
Definition at line 133 of file PiggyList.h.
Referenced by souffle::PiggyList< std::atomic< block_t > >::append(), souffle::PiggyList< std::atomic< block_t > >::clear(), souffle::PiggyList< std::atomic< block_t > >::createNode(), and souffle::PiggyList< std::atomic< block_t > >::PiggyList().
template<class T> std::atomic<size_t> souffle::PiggyList< T >::m_size private
Definition at line 134 of file PiggyList.h.
Referenced by souffle::PiggyList< std::atomic< block_t > >::append(), souffle::PiggyList< std::atomic< block_t > >::clear(), souffle::PiggyList< std::atomic< block_t > >::createNode(), souffle::PiggyList< std::atomic< block_t > >::PiggyList(), and souffle::PiggyList< std::atomic< block_t > >::size().
template<class T> constexpr size_t souffle::PiggyList< T >::max_conts = 64 static private
Definition at line 137 of file PiggyList.h.
template<class T> std::atomic<size_t> souffle::PiggyList< T >::num_containers private
Definition at line 131 of file PiggyList.h.
Referenced by souffle::PiggyList< std::atomic< block_t > >::append(), souffle::PiggyList< std::atomic< block_t > >::clear(), souffle::PiggyList< std::atomic< block_t > >::createNode(), souffle::PiggyList< std::atomic< block_t > >::freeList(), and souffle::PiggyList< std::atomic< block_t > >::PiggyList().
template<class T> SpinLock souffle::PiggyList< T >::sl mutable private
Definition at line 141 of file PiggyList.h.
Referenced by souffle::PiggyList< std::atomic< block_t > >::append(), souffle::PiggyList< std::atomic< block_t > >::createNode(), and souffle::PiggyList< std::atomic< block_t > >::freeList().
The documentation for this class was generated from the following file:
PiggyList.h