souffle: souffle::RamRelationReference Class Reference
souffle::RamRelationReference Class Reference
A RAM Relation in the RAM intermediate representation.
#include <RamRelation.h>
Public Member Functions
void apply (const RamNodeMapper &map) override
Apply mapper.
RamRelationReference * clone () const override
Create clone.
const std::string getArg (uint32_t i) const
Get argument.
const std::string getArgTypeQualifier (uint32_t i) const
Get argument qualifier.
unsigned getArity () const
Get arity.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of child nodes.
const std::string & getName () const
Get name.
const RamRelation * getRelation () const
Get relation.
const RelationRepresentation getRepresentation () const
Relation representation type.
const SymbolMask & getSymbolMask () const
Get symbol mask.
const bool isComputed () const
Is computed relation.
const bool isInput () const
Is input relation.
const bool isNullary () const
Is nullary relation.
const bool isOutput () const
Is output relation.
const bool isTemp () const
Is temp relation.
bool operator< (const RamRelationReference &other) const
Comparator.
void print (std::ostream &out) const override
Print RAM node.
RamRelationReference (const RamRelation *relation)
Public Member Functions inherited from souffle::RamNode
RamNodeType getNodeType () const
Get type of node.
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
RamNode (RamNodeType type)
virtual ~RamNode ()=default
A virtual destructor for RAM nodes.
Protected Member Functions
bool equal (const RamNode &node) const override
Check equality.
Protected Attributes
const RamRelation * relation
Name of relation.
Detailed Description
A RAM Relation in the RAM intermediate representation.
Definition at line 189 of file RamRelation.h.
Constructor & Destructor Documentation
souffle::RamRelationReference::RamRelationReference (const RamRelation * relation) inline
Definition at line 195 of file RamRelation.h.
Referenced by clone().
 : RamNode(RN_RelationReference), relation(relation) {}
Member Function Documentation
void souffle::RamRelationReference::apply (const RamNodeMapper & map) inline override virtual
Apply mapper.
Implements souffle::RamNode.
Definition at line 279 of file RamRelation.h.
 {}
RamRelationReference* souffle::RamRelationReference::clone () const inline override virtual
Create clone.
Implements souffle::RamNode.
Definition at line 273 of file RamRelation.h.
References RamRelationReference(), and relation.
Referenced by souffle::CreateIndicesTransformer::rewriteScan().
{
         auto* res = new RamRelationReference(relation);
         return res;
     }
bool souffle::RamRelationReference::equal (const RamNode & node) const inline override protected virtual
Check equality.
Implements souffle::RamNode.
Definition at line 283 of file RamRelation.h.
References relation.
{
         assert(nullptr != dynamic_cast<const RamRelationReference*>(&node));
         const auto& other = static_cast<const RamRelationReference&>(node);
         return relation == other.relation;
     }
const std::string souffle::RamRelationReference::getArg (uint32_t i) const inline
Get argument.
Definition at line 248 of file RamRelation.h.
References souffle::RamRelation::getArg(), and relation.
Referenced by souffle::AstTranslator::ClauseTranslator::indexValues(), souffle::RamCreate::print(), souffle::RamIndexScan::print(), and souffle::IndexSetAnalysis::print().
{
         return relation->getArg(i);
     }
const std::string souffle::RamRelationReference::getArgTypeQualifier (uint32_t i) const inline
Get argument qualifier.
Definition at line 253 of file RamRelation.h.
References souffle::RamRelation::getArgTypeQualifier(), and relation.
{
         return relation->getArgTypeQualifier(i);
     }
unsigned souffle::RamRelationReference::getArity () const inline
Get arity.
Definition at line 208 of file RamRelation.h.
References souffle::RamRelation::getArity(), and relation.
Referenced by souffle::Synthesiser::emitCode(), souffle::Interpreter::evalOp(), souffle::Interpreter::evalStmt(), souffle::Synthesiser::generateCode(), souffle::SynthesiserRelation::getArity(), souffle::SynthesiserRelation::getSynthesiserRelation(), souffle::RamCreate::print(), souffle::IndexSetAnalysis::print(), souffle::RamIndexScan::print(), and souffle::CreateIndicesTransformer::rewriteScan().
{
         return relation->getArity();
     }
std::vector<const RamNode*> souffle::RamRelationReference::getChildNodes () const inline override virtual
Obtain list of child nodes.
Implements souffle::RamNode.
Definition at line 268 of file RamRelation.h.
{
         return std::vector<const RamNode*>();  // no child nodes
     }
const std::string& souffle::RamRelationReference::getName () const inline
Get name.
Definition at line 198 of file RamRelation.h.
References souffle::RamRelation::getName(), and relation.
Referenced by souffle::Synthesiser::emitCode(), souffle::Interpreter::evalCond(), souffle::Interpreter::evalStmt(), souffle::Interpreter::executeMain(), souffle::Synthesiser::generateCode(), souffle::IndexSetAnalysis::getIndexes(), souffle::Synthesiser::getRelationName(), souffle::RamCreate::print(), souffle::RamLoad::print(), souffle::RamStore::print(), souffle::RamClear::print(), souffle::RamScan::print(), souffle::RamDrop::print(), souffle::RamIndexScan::print(), print(), souffle::RamFact::print(), souffle::RamLogSize::print(), souffle::RamPrintSize::print(), and souffle::Interpreter::swapRelation().
{
         return relation->getName();
     }
const RamRelation* souffle::RamRelationReference::getRelation () const inline
Get relation.
Definition at line 203 of file RamRelation.h.
References relation.
Referenced by souffle::RamRelationStatement::equal(), souffle::RamRelationSearch::equal(), souffle::RamExists::equal(), souffle::RamProvenanceExists::equal(), souffle::RamEmpty::equal(), souffle::RamAggregate::equal(), souffle::RamProject::equal(), and operator<().
{
         return relation;
     }
const RelationRepresentation souffle::RamRelationReference::getRepresentation () const inline
Relation representation type.
Definition at line 218 of file RamRelation.h.
References souffle::RamRelation::getRepresentation(), and relation.
Referenced by souffle::Synthesiser::emitCode(), souffle::SynthesiserRelation::getSynthesiserRelation(), and souffle::RamCreate::print().
{
         return relation->getRepresentation();
     }
const SymbolMask& souffle::RamRelationReference::getSymbolMask () const inline
Get symbol mask.
Definition at line 243 of file RamRelation.h.
References souffle::RamRelation::getSymbolMask(), and relation.
Referenced by souffle::Synthesiser::emitCode(), souffle::Interpreter::evalStmt(), and souffle::Synthesiser::generateCode().
{
         return relation->getSymbolMask();
     }
const bool souffle::RamRelationReference::isComputed () const inline
Is computed relation.
Definition at line 233 of file RamRelation.h.
References souffle::RamRelation::isComputed(), and relation.
{
         return relation->isComputed();
     }
const bool souffle::RamRelationReference::isInput () const inline
Is input relation.
Definition at line 228 of file RamRelation.h.
References souffle::RamRelation::isInput(), and relation.
{
         return relation->isInput();
     }
const bool souffle::RamRelationReference::isNullary () const inline
Is nullary relation.
Definition at line 213 of file RamRelation.h.
References souffle::RamRelation::isNullary(), and relation.
Referenced by souffle::Synthesiser::emitCode(), and souffle::SynthesiserRelation::getSynthesiserRelation().
{
         return relation->isNullary();
     }
const bool souffle::RamRelationReference::isOutput () const inline
Is output relation.
Definition at line 238 of file RamRelation.h.
References souffle::RamRelation::isOutput(), and relation.
{
         return relation->isOutput();
     }
const bool souffle::RamRelationReference::isTemp () const inline
Is temp relation.
Definition at line 223 of file RamRelation.h.
References souffle::RamRelation::isTemp(), and relation.
Referenced by souffle::Synthesiser::emitCode(), souffle::Interpreter::evalCond(), and souffle::Synthesiser::generateCode().
{
         return relation->isTemp();
     }
bool souffle::RamRelationReference::operator< (const RamRelationReference & other) const inline
Comparator.
Definition at line 258 of file RamRelation.h.
References getRelation(), and relation.
{
         return relation->operator<(*other.getRelation());
     }
void souffle::RamRelationReference::print (std::ostream & out) const inline override virtual
Print RAM node.
Implements souffle::RamNode.
Definition at line 263 of file RamRelation.h.
References getName().
{
         out << getName();
     }
Field Documentation
const RamRelation* souffle::RamRelationReference::relation protected
Name of relation.
Definition at line 192 of file RamRelation.h.
Referenced by clone(), equal(), getArg(), getArgTypeQualifier(), getArity(), getName(), getRelation(), getRepresentation(), getSymbolMask(), isComputed(), isInput(), isNullary(), isOutput(), isTemp(), and operator<().
The documentation for this class was generated from the following file:
RamRelation.h