souffle: souffle::RamSearch Class Reference
souffle::RamSearch Class Reference
Abstract class for relation searches and lookups.
#include <RamOperation.h>
Public Member Functions
std::size_t getIdentifier () const
Get identifier.
const std::string & getProfileText () const
Get profile text.
RamSearch (RamNodeType type, size_t ident, std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamNestedOperation
void apply (const RamNodeMapper &map) override
Apply mapper.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of child nodes.
RamOperation & getOperation () const
Get nested operation.
void print (std::ostream &os, int tabpos) const override
Print.
RamNestedOperation (RamNodeType type, std::unique_ptr< RamOperation > nested)
Public Member Functions inherited from souffle::RamOperation
RamOperation * clone () const override=0
Create clone.
void print (std::ostream &os) const override
Pretty print.
RamOperation (RamNodeType type)
Public Member Functions inherited from souffle::RamNode
RamNodeType getNodeType () const
Get type of node.
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
RamNode (RamNodeType type)
virtual ~RamNode ()=default
A virtual destructor for RAM nodes.
Protected Member Functions
bool equal (const RamNode &node) const override
Check equality.
Private Attributes
size_t identifier
Identifier for the tuple.
const std::string profileText
Profile text.
Detailed Description
Abstract class for relation searches and lookups.
Definition at line 110 of file RamOperation.h.
Constructor & Destructor Documentation
souffle::RamSearch::RamSearch (RamNodeType type, size_t ident, std::unique_ptr< RamOperation > nested, std::string profileText = "") inline
Definition at line 118 of file RamOperation.h.
             : RamNestedOperation(type, std::move(nested)), identifier(ident),
               profileText(std::move(profileText)) {}
Member Function Documentation
bool souffle::RamSearch::equal (const RamNode & node) const inline override protected virtual
Check equality.
Reimplemented from souffle::RamNestedOperation.
Reimplemented in souffle::RamAggregate, souffle::RamLookup, souffle::RamIndexScan, and souffle::RamRelationSearch.
Definition at line 135 of file RamOperation.h.
References souffle::RamNestedOperation::equal(), getIdentifier(), and getProfileText().
Referenced by souffle::RamRelationSearch::equal(), souffle::RamLookup::equal(), and souffle::RamAggregate::equal().
{
         assert(nullptr != dynamic_cast<const RamSearch*>(&node));
         const auto& other = static_cast<const RamSearch&>(node);
         return RamNestedOperation::equal(other) && getIdentifier() == other.getIdentifier() &&
                getProfileText() == other.getProfileText();
     }
std::size_t souffle::RamSearch::getIdentifier () const inline
Get identifier.
Definition at line 124 of file RamOperation.h.
References identifier.
Referenced by souffle::RamAggregate::addCondition(), souffle::RamScan::clone(), souffle::RamIndexScan::clone(), souffle::RamLookup::clone(), souffle::RamAggregate::clone(), souffle::Synthesiser::emitCode(), equal(), souffle::Interpreter::evalOp(), souffle::RamScan::print(), souffle::RamIndexScan::print(), souffle::RamLookup::print(), souffle::RamAggregate::print(), and souffle::CreateIndicesTransformer::rewriteScan().
{
         return identifier;
     }
const std::string& souffle::RamSearch::getProfileText () const inline
Get profile text.
Definition at line 129 of file RamOperation.h.
References profileText.
Referenced by souffle::RamScan::clone(), souffle::RamIndexScan::clone(), souffle::Synthesiser::emitCode(), equal(), souffle::Interpreter::evalOp(), souffle::Interpreter::executeMain(), and souffle::CreateIndicesTransformer::rewriteScan().
{
         return profileText;
     }
Field Documentation
size_t souffle::RamSearch::identifier private
Identifier for the tuple.
Definition at line 112 of file RamOperation.h.
Referenced by getIdentifier().
const std::string souffle::RamSearch::profileText private
Profile text.
Definition at line 115 of file RamOperation.h.
Referenced by getProfileText().
The documentation for this class was generated from the following file:
RamOperation.h