souffle: souffle::RamNot Class Reference
souffle::RamNot Class Reference
Negation.
#include <RamCondition.h>
Public Member Functions
void apply (const RamNodeMapper &map) override
Apply.
RamNot * clone () const override
Create clone.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of child nodes.
const RamCondition & getOperand () const
Get operand of negation.
void print (std::ostream &os) const override
Print.
RamNot (std::unique_ptr< RamCondition > operand)
Public Member Functions inherited from souffle::RamCondition
RamCondition (RamNodeType type)
Public Member Functions inherited from souffle::RamNode
RamNodeType getNodeType () const
Get type of node.
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
RamNode (RamNodeType type)
virtual ~RamNode ()=default
A virtual destructor for RAM nodes.
Protected Member Functions
bool equal (const RamNode &node) const override
Check equality.
Protected Attributes
std::unique_ptr< RamCondition > operand
Condition to be negated.
Detailed Description
Negation.
Definition at line 111 of file RamCondition.h.
Constructor & Destructor Documentation
souffle::RamNot::RamNot (std::unique_ptr< RamCondition > operand) inline
Definition at line 117 of file RamCondition.h.
Referenced by clone().
 : RamCondition(RN_Not), operand(std::move(operand)) {}
Member Function Documentation
void souffle::RamNot::apply (const RamNodeMapper & map) inline override virtual
Apply.
Implements souffle::RamNode.
Definition at line 143 of file RamCondition.h.
References operand.
{
         operand = map(std::move(operand));
     }
RamNot* souffle::RamNot::clone () const inline override virtual
Create clone.
Implements souffle::RamCondition.
Definition at line 137 of file RamCondition.h.
References operand, and RamNot().
{
         RamNot* res = new RamNot(std::unique_ptr<RamCondition>(operand->clone()));
         return res;
     }
bool souffle::RamNot::equal (const RamNode & node) const inline override protected virtual
Check equality.
Implements souffle::RamNode.
Definition at line 149 of file RamCondition.h.
References getOperand().
{
         assert(nullptr != dynamic_cast<const RamNot*>(&node));
         const auto& other = static_cast<const RamNot&>(node);
         return getOperand() == other.getOperand();
     }
std::vector<const RamNode*> souffle::RamNot::getChildNodes () const inline override virtual
Obtain list of child nodes.
Implements souffle::RamNode.
Definition at line 132 of file RamCondition.h.
References operand.
{
         return {operand.get()};
     }
const RamCondition& souffle::RamNot::getOperand () const inline
Get operand of negation.
Definition at line 120 of file RamCondition.h.
References operand.
Referenced by souffle::Synthesiser::emitCode(), equal(), souffle::Interpreter::evalCond(), souffle::RamConditionLevelAnalysis::getLevel(), and souffle::getLevel().
{
         assert(nullptr != operand);
         return *operand;
     }
void souffle::RamNot::print (std::ostream & os) const inline override virtual
Print.
Implements souffle::RamNode.
Definition at line 126 of file RamCondition.h.
References operand.
{
         os << "not ";
         operand->print(os);
     }
Field Documentation
std::unique_ptr<RamCondition> souffle::RamNot::operand protected
Condition to be negated.
Definition at line 114 of file RamCondition.h.
Referenced by apply(), clone(), getChildNodes(), getOperand(), and print().
The documentation for this class was generated from the following file:
RamCondition.h