souffle: souffle::AstIntrinsicFunctor Class Reference
souffle::AstIntrinsicFunctor Class Reference
Subclass of AstFunctor that represents an intrinsic (built-in) functor.
#include <AstArgument.h>
Public Member Functions
bool acceptsNumbers (size_t arg) const
Check if the argument of this functor is a number type.
bool acceptsSymbols (size_t arg) const
Check if the argument of this functor is a symbol type.
void apply (const AstNodeMapper &map) override
Mutates this node.
template<typename... Operands>
AstIntrinsicFunctor (FunctorOp function, Operands...operands)
AstIntrinsicFunctor (FunctorOp function, std::vector< std::unique_ptr< AstArgument >> operands)
AstIntrinsicFunctor * clone () const override
Clone this node.
AstArgument * getArg (size_t idx) const
std::vector< AstArgument * > getArguments () const
size_t getArity () const
std::vector< const AstNode * > getChildNodes () const override
Obtains a list of all embedded child nodes.
FunctorOp getFunction () const
bool isNumerical () const
Check if the return value of this functor is a number type.
bool isSymbolic () const
Check if the return value of this functor is a symbol type.
void print (std::ostream &os) const override
Print argument to the given output stream.
void setArg (size_t idx, std::unique_ptr< AstArgument > arg)
Public Member Functions inherited from souffle::AstArgument
~AstArgument () override=default
Public Member Functions inherited from souffle::AstNode
std::string extloc () const
Return source location of the syntactic element.
SrcLocation getSrcLoc () const
Return source location of the AstNode.
bool operator!= (const AstNode &other) const
Inequality check for two AST nodes.
bool operator== (const AstNode &other) const
Equivalence check for two AST nodes.
void setSrcLoc (const SrcLocation &l)
Set source location for the AstNode.
virtual ~AstNode ()=default
Protected Member Functions
bool equal (const AstNode &node) const override
Implements the node comparison for this node type.
Protected Attributes
std::vector< std::unique_ptr
< AstArgument > > args
FunctorOp function
Detailed Description
Subclass of AstFunctor that represents an intrinsic (built-in) functor.
Definition at line 277 of file AstArgument.h.
Constructor & Destructor Documentation
template<typename... Operands> souffle::AstIntrinsicFunctor::AstIntrinsicFunctor (FunctorOp function, Operands... operands) inline
Definition at line 284 of file AstArgument.h.
References args, and souffle::getFunctorOpArity().
Referenced by clone().
                                                                   : function(function) {
         std::unique_ptr<AstArgument> tmp[] = {std::move(operands)...};
         for (auto& cur : tmp) {
             args.push_back(std::move(cur));
         }
         // TODO (#761): eventually allow non-fixed functor arity
         assert(getFunctorOpArity(function) == args.size() && "invalid number of arguments for functor");
     }
souffle::AstIntrinsicFunctor::AstIntrinsicFunctor (FunctorOp function, std::vector< std::unique_ptr< AstArgument >> operands) inline
Definition at line 294 of file AstArgument.h.
             : function(function), args(std::move(operands)){};
Member Function Documentation
bool souffle::AstIntrinsicFunctor::acceptsNumbers (size_t arg) const inline
Check if the argument of this functor is a number type.
Definition at line 330 of file AstArgument.h.
References souffle::functorOpAcceptsNumbers().
Referenced by souffle::TypeAnalysis::analyseTypes(), and souffle::AstSemanticChecker::checkProgram().
{
         return functorOpAcceptsNumbers(arg, function);
     }
bool souffle::AstIntrinsicFunctor::acceptsSymbols (size_t arg) const inline
Check if the argument of this functor is a symbol type.
Definition at line 335 of file AstArgument.h.
References souffle::functorOpAcceptsSymbols().
Referenced by souffle::TypeAnalysis::analyseTypes(), and souffle::AstSemanticChecker::checkProgram().
{
         return functorOpAcceptsSymbols(arg, function);
     }
void souffle::AstIntrinsicFunctor::apply (const AstNodeMapper & map) inline override virtual
Mutates this node.
Implements souffle::AstNode.
Definition at line 365 of file AstArgument.h.
References args.
{
         for (auto& arg : args) {
             arg = map(std::move(arg));
         }
     }
AstIntrinsicFunctor* souffle::AstIntrinsicFunctor::clone () const inline override virtual
Clone this node.
Implements souffle::AstArgument.
Definition at line 354 of file AstArgument.h.
References args, AstIntrinsicFunctor(), and souffle::AstNode::getSrcLoc().
Referenced by souffle::getInlinedArgument().
{
         std::vector<std::unique_ptr<AstArgument>> argsCopy;
         for (auto& arg : args) {
             argsCopy.push_back(std::unique_ptr<AstArgument>(arg->clone()));
         }
         auto res = new AstIntrinsicFunctor(function, std::move(argsCopy));
         res->setSrcLoc(getSrcLoc());
         return res;
     }
bool souffle::AstIntrinsicFunctor::equal (const AstNode & node) const inline override protected virtual
Implements the node comparison for this node type.
Implements souffle::AstNode.
Definition at line 382 of file AstArgument.h.
References args, souffle::equal_targets(), and function.
{
         assert(nullptr != dynamic_cast<const AstIntrinsicFunctor*>(&node));
         const auto& other = static_cast<const AstIntrinsicFunctor&>(node);
         return function == other.function && equal_targets(args, other.args);
     }
AstArgument* souffle::AstIntrinsicFunctor::getArg (size_t idx) const inline
Definition at line 297 of file AstArgument.h.
References args.
Referenced by souffle::TypeAnalysis::analyseTypes(), and souffle::AstSemanticChecker::checkProgram().
{
         assert(idx >= 0 && idx < args.size() && "wrong argument");
         return args[idx].get();
     }
std::vector<AstArgument*> souffle::AstIntrinsicFunctor::getArguments () const inline
Definition at line 310 of file AstArgument.h.
References args, and souffle::toPtrVector().
Referenced by souffle::getGroundedTerms(), and souffle::AstTranslator::translateValue().
{
         return toPtrVector(args);
     }
size_t souffle::AstIntrinsicFunctor::getArity () const inline
Definition at line 306 of file AstArgument.h.
References args.
Referenced by souffle::TypeAnalysis::analyseTypes(), and souffle::AstSemanticChecker::checkProgram().
{
         return args.size();
     }
std::vector<const AstNode*> souffle::AstIntrinsicFunctor::getChildNodes () const inline override virtual
Obtains a list of all embedded child nodes.
Reimplemented from souffle::AstArgument.
Definition at line 372 of file AstArgument.h.
References args, and souffle::AstArgument::getChildNodes().
{
         auto res = AstArgument::getChildNodes();
         for (auto& arg : args) {
             res.push_back(arg.get());
         }
         return res;
     }
FunctorOp souffle::AstIntrinsicFunctor::getFunction () const inline
Definition at line 302 of file AstArgument.h.
Referenced by souffle::AstTranslator::translateValue().
{
         return function;
     }
bool souffle::AstIntrinsicFunctor::isNumerical () const inline
Check if the return value of this functor is a number type.
Definition at line 320 of file AstArgument.h.
References souffle::isNumericFunctorOp().
Referenced by souffle::TypeAnalysis::analyseTypes(), and souffle::AstSemanticChecker::checkProgram().
{
         return isNumericFunctorOp(function);
     }
bool souffle::AstIntrinsicFunctor::isSymbolic () const inline
Check if the return value of this functor is a symbol type.
Definition at line 325 of file AstArgument.h.
References souffle::isSymbolicFunctorOp().
Referenced by souffle::TypeAnalysis::analyseTypes(), and souffle::AstSemanticChecker::checkProgram().
{
         return isSymbolicFunctorOp(function);
     }
void souffle::AstIntrinsicFunctor::print (std::ostream & os) const inline override virtual
Print argument to the given output stream.
Implements souffle::AstNode.
Definition at line 340 of file AstArgument.h.
References args, souffle::getSymbolForFunctorOp(), souffle::isInfixFunctorOp(), and souffle::join().
{
         if (isInfixFunctorOp(function)) {
             os << "(";
             os << join(args, getSymbolForFunctorOp(function), print_deref<std::unique_ptr<AstArgument>>());
             os << ")";
         } else {
             os << getSymbolForFunctorOp(function);
             os << "(";
             os << join(args, ",", print_deref<std::unique_ptr<AstArgument>>());
             os << ")";
         }
     }
void souffle::AstIntrinsicFunctor::setArg (size_t idx, std::unique_ptr< AstArgument > arg) inline
Definition at line 314 of file AstArgument.h.
References args.
Referenced by souffle::getInlinedArgument().
{
         assert(idx >= 0 && idx < args.size() && "wrong argument");
         args[idx] = std::move(arg);
     }
Field Documentation
std::vector<std::unique_ptr<AstArgument> > souffle::AstIntrinsicFunctor::args protected
Definition at line 280 of file AstArgument.h.
Referenced by apply(), AstIntrinsicFunctor(), clone(), equal(), getArg(), getArguments(), getArity(), getChildNodes(), print(), and setArg().
FunctorOp souffle::AstIntrinsicFunctor::function protected
Definition at line 279 of file AstArgument.h.
Referenced by equal().
The documentation for this class was generated from the following file:
AstArgument.h