souffle: souffle::RamReturn Class Reference
souffle::RamReturn Class Reference
A statement for returning from a ram subroutine.
#include <RamOperation.h>
Public Member Functions
void addValue (std::unique_ptr< RamValue > val)
void apply (const RamNodeMapper &map) override
Apply mapper.
RamReturn * clone () const override
Create clone.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of child nodes.
RamValue & getValue (size_t i) const
Get value.
std::vector< RamValue * > getValues () const
void print (std::ostream &os, int tabpos) const override
Print.
RamReturn ()
Public Member Functions inherited from souffle::RamOperation
void print (std::ostream &os) const override
Pretty print.
RamOperation (RamNodeType type)
Public Member Functions inherited from souffle::RamNode
RamNodeType getNodeType () const
Get type of node.
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
RamNode (RamNodeType type)
virtual ~RamNode ()=default
A virtual destructor for RAM nodes.
Protected Member Functions
bool equal (const RamNode &node) const override
Check equality.
Protected Attributes
std::vector< std::unique_ptr
< RamValue > > values
Detailed Description
A statement for returning from a ram subroutine.
Definition at line 716 of file RamOperation.h.
Constructor & Destructor Documentation
souffle::RamReturn::RamReturn () inline
Definition at line 721 of file RamOperation.h.
Referenced by clone().
 : RamOperation(RN_Return) {}
Member Function Documentation
void souffle::RamReturn::addValue (std::unique_ptr< RamValue > val) inline
Definition at line 744 of file RamOperation.h.
References values.
{
         values.push_back(std::move(val));
     }
void souffle::RamReturn::apply (const RamNodeMapper & map) inline override virtual
Apply mapper.
Implements souffle::RamOperation.
Definition at line 777 of file RamOperation.h.
References values.
{
         for (auto& cur : values) {
             cur = map(std::move(cur));
         }
     }
RamReturn* souffle::RamReturn::clone () const inline override virtual
Create clone.
Implements souffle::RamOperation.
Definition at line 768 of file RamOperation.h.
References RamReturn(), and values.
{
         auto* res = new RamReturn();
         for (auto& cur : values) {
             res->values.push_back(std::unique_ptr<RamValue>(cur->clone()));
         }
         return res;
     }
bool souffle::RamReturn::equal (const RamNode & node) const inline override protected virtual
Check equality.
Implements souffle::RamOperation.
Definition at line 785 of file RamOperation.h.
References souffle::equal_targets(), and values.
{
         assert(nullptr != dynamic_cast<const RamReturn*>(&node));
         const auto& other = static_cast<const RamReturn&>(node);
         return equal_targets(values, other.values);
     }
std::vector<const RamNode*> souffle::RamReturn::getChildNodes () const inline override virtual
Obtain list of child nodes.
Implements souffle::RamOperation.
Definition at line 759 of file RamOperation.h.
References values.
{
         std::vector<const RamNode*> res;
         for (const auto& cur : values) {
             res.push_back(cur.get());
         }
         return res;
     }
RamValue& souffle::RamReturn::getValue (size_t i) const inline
Get value.
Definition at line 753 of file RamOperation.h.
References i, and values.
{
         assert(i < values.size() && "value index out of range");
         return *values[i];
     }
std::vector<RamValue*> souffle::RamReturn::getValues () const inline
Definition at line 748 of file RamOperation.h.
References souffle::toPtrVector(), and values.
Referenced by souffle::Synthesiser::emitCode(), souffle::Interpreter::evalOp(), and print().
{
         return toPtrVector(values);
     }
void souffle::RamReturn::print (std::ostream & os, int tabpos) const inline override virtual
Print.
Implements souffle::RamOperation.
Definition at line 723 of file RamOperation.h.
References getValues().
{
         const std::string tabs(tabpos, '\t');
         // return
         os << tabs << "RETURN (";
         for (auto val : getValues()) {
             if (val == nullptr) {
                 os << "_";
             } else {
                 val->print(os);
             }
             if (val != *(getValues().end() - 1)) {
                 os << ", ";
             }
         }
         os << ")";
     }
Field Documentation
std::vector<std::unique_ptr<RamValue> > souffle::RamReturn::values protected
Definition at line 718 of file RamOperation.h.
Referenced by addValue(), apply(), clone(), equal(), getChildNodes(), getValue(), and getValues().
The documentation for this class was generated from the following file:
RamOperation.h