souffle: souffle::RamAggregate Class Reference
souffle::RamAggregate Class Reference
Aggregation.
#include <RamOperation.h>
Public Types
enum Function { MAX, MIN, COUNT, SUM }
Types of aggregation functions.
Public Member Functions
void addCondition (std::unique_ptr< RamCondition > newCondition)
Add condition.
void apply (const RamNodeMapper &map) override
Apply mapper.
RamAggregate * clone () const override
Create clone.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of child nodes.
RamCondition * getCondition () const
Get condition.
Function getFunction () const
Get aggregation function.
std::unique_ptr< RamValue > getIndexElement (RamCondition *c, size_t &element, size_t level)
Get indexable element.
std::vector< RamValue * > getPattern () const
Get pattern.
SearchColumns getRangeQueryColumns () const
Get range query columns.
const RamRelationReference & getRelation () const
Get relation.
const RamValue * getTargetExpression () const
Get target expression.
void print (std::ostream &os, int tabpos) const override
Print.
RamAggregate (std::unique_ptr< RamOperation > nested, Function fun, std::unique_ptr< RamValue > value, std::unique_ptr< RamRelationReference > rel, size_t ident)
Public Member Functions inherited from souffle::RamSearch
std::size_t getIdentifier () const
Get identifier.
const std::string & getProfileText () const
Get profile text.
RamSearch (RamNodeType type, size_t ident, std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamNestedOperation
RamOperation & getOperation () const
Get nested operation.
RamNestedOperation (RamNodeType type, std::unique_ptr< RamOperation > nested)
Public Member Functions inherited from souffle::RamOperation
void print (std::ostream &os) const override
Pretty print.
RamOperation (RamNodeType type)
Public Member Functions inherited from souffle::RamNode
RamNodeType getNodeType () const
Get type of node.
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
RamNode (RamNodeType type)
virtual ~RamNode ()=default
A virtual destructor for RAM nodes.
Protected Member Functions
bool equal (const RamNode &node) const override
Check equality.
Private Attributes
std::unique_ptr< RamCondition > condition
Condition that is checked for each obtained tuple.
Function function
Aggregation function.
SearchColumns keys = 0
Columns to be matched when using a range query.
std::vector< std::unique_ptr
< RamValue > > pattern
Pattern for filtering tuples.
std::unique_ptr
< RamRelationReference > relation
Aggregation relation.
std::unique_ptr< RamValue > value
Aggregation value.
Detailed Description
Aggregation.
Definition at line 388 of file RamOperation.h.
Member Enumeration Documentation
enum souffle::RamAggregate::Function
Types of aggregation functions.
Enumerator
MAX
MIN
COUNT
SUM
Definition at line 391 of file RamOperation.h.
 { MAX, MIN, COUNT, SUM };
Constructor & Destructor Documentation
souffle::RamAggregate::RamAggregate (std::unique_ptr< RamOperation > nested, Function fun, std::unique_ptr< RamValue > value, std::unique_ptr< RamRelationReference > rel, size_t ident) inline
Definition at line 418 of file RamOperation.h.
Referenced by clone().
             : RamSearch(RN_Aggregate, ident, std::move(nested)), function(fun), value(std::move(value)),
               relation(std::move(rel)), pattern(relation->getArity()) {}
Member Function Documentation
void souffle::RamAggregate::addCondition (std::unique_ptr< RamCondition > newCondition)
Add condition.
add condition
Definition at line 223 of file RamOperation.cpp.
References condition, souffle::EQ, souffle::RamSearch::getIdentifier(), getIndexElement(), souffle::getLevel(), keys, pattern, relation, and value.
{
     assert(getLevel(newCondition.get()) == getIdentifier());
     // use condition to narrow scan if possible
     size_t element = 0;
     if (std::unique_ptr<RamValue> value = getIndexElement(newCondition.get(), element, getIdentifier())) {
         if (element > 0 || relation->getName().find("__agg") == std::string::npos) {
             keys |= (1 << element);
             if (pattern[element] == nullptr) {
                 pattern[element] = std::move(value);
             } else {
                 std::unique_ptr<RamValue> field(new RamElementAccess(getIdentifier(), element));
                 auto addCondition = [&](std::unique_ptr<RamCondition> c) {
                     assert(getLevel(c.get()) == getIdentifier());
                     if (condition != nullptr) {
                         condition = std::make_unique<RamAnd>(std::move(condition), std::move(c));
                     } else {
                         condition = std::move(c);
                     }
                 };
                 addCondition(std::make_unique<RamBinaryRelation>(
                         BinaryConstraintOp::EQ, std::move(field), std::move(value)));
             }
         } else {
             std::unique_ptr<RamValue> field(new RamElementAccess(getIdentifier(), element));
             std::unique_ptr<RamCondition> eq(
                     new RamBinaryRelation(BinaryConstraintOp::EQ, std::move(field), std::move(value)));
             if (condition != nullptr) {
                 condition = std::make_unique<RamAnd>(std::move(condition), std::move(eq));
             } else {
                 condition.swap(eq);
             }
         }
     }
 }
void souffle::RamAggregate::apply (const RamNodeMapper & map) inline override virtual
Apply mapper.
Reimplemented from souffle::RamNestedOperation.
Definition at line 526 of file RamOperation.h.
References souffle::RamNestedOperation::apply(), condition, pattern, relation, and value.
{
         RamSearch::apply(map);
         if (condition != nullptr) {
             condition = map(std::move(condition));
         }
         relation = map(std::move(relation));
         if (value != nullptr) {
             value = map(std::move(value));
         }
         for (auto& cur : pattern) {
             if (cur) {
                 cur = map(std::move(cur));
             }
         }
     }
RamAggregate* souffle::RamAggregate::clone () const inline override virtual
Create clone.
Implements souffle::RamOperation.
Definition at line 512 of file RamOperation.h.
References souffle::RamSearch::getIdentifier(), souffle::RamNestedOperation::getOperation(), i, keys, pattern, RamAggregate(), relation, and value.
{
         RamAggregate* res = new RamAggregate(std::unique_ptr<RamOperation>(getOperation().clone()), function,
                 value == nullptr ? nullptr : std::unique_ptr<RamValue>(value->clone()),
                 std::unique_ptr<RamRelationReference>(relation->clone()), getIdentifier());
         res->keys = keys;
         for (size_t i = 0; i < pattern.size(); ++i) {
             if (pattern[i] != nullptr) {
                 res->pattern[i] = std::unique_ptr<RamValue>(pattern[i]->clone());
             }
         }
         return res;
     }
bool souffle::RamAggregate::equal (const RamNode & node) const inline override protected virtual
Check equality.
Reimplemented from souffle::RamSearch.
Definition at line 544 of file RamOperation.h.
References souffle::RamSearch::equal(), souffle::equal_targets(), getCondition(), getFunction(), getRangeQueryColumns(), souffle::RamRelationReference::getRelation(), getRelation(), getTargetExpression(), and pattern.
{
         assert(nullptr != dynamic_cast<const RamAggregate*>(&node));
         const auto& other = static_cast<const RamAggregate&>(node);
         if (getCondition() != nullptr && other.getCondition() != nullptr &&
                 *getCondition() != *other.getCondition()) {
             return false;
         }
         return RamSearch::equal(other) && getCondition() == other.getCondition() &&
                getFunction() == other.getFunction() && getRelation() == other.getRelation() &&
                getTargetExpression() == other.getTargetExpression() &&
                equal_targets(pattern, other.pattern) &&
                getRangeQueryColumns() == other.getRangeQueryColumns();
     }
std::vector<const RamNode*> souffle::RamAggregate::getChildNodes () const inline override virtual
Obtain list of child nodes.
Reimplemented from souffle::RamNestedOperation.
Definition at line 503 of file RamOperation.h.
References condition, and souffle::RamNestedOperation::getChildNodes().
{
         auto res = RamSearch::getChildNodes();
         if (condition) {
             res.push_back(condition.get());
         }
         return res;
     }
RamCondition* souffle::RamAggregate::getCondition () const inline
Get condition.
Definition at line 424 of file RamOperation.h.
References condition.
Referenced by souffle::Synthesiser::emitCode(), equal(), and print().
{
         return condition.get();
     }
Function souffle::RamAggregate::getFunction () const inline
Get aggregation function.
Definition at line 429 of file RamOperation.h.
Referenced by souffle::Synthesiser::emitCode(), equal(), and souffle::Interpreter::evalOp().
{
         return function;
     }
std::unique_ptr< RamValue > souffle::RamAggregate::getIndexElement (RamCondition * c, size_t & element, size_t level)
Get indexable element.
get indexable element
Definition at line 200 of file RamOperation.cpp.
References souffle::EQ, souffle::getLevel(), souffle::isConstant(), lhs, and rhs.
Referenced by addCondition().
{
     if (auto* binRelOp = dynamic_cast<RamBinaryRelation*>(c)) {
         if (binRelOp->getOperator() == BinaryConstraintOp::EQ) {
             if (auto* lhs = dynamic_cast<RamElementAccess*>(binRelOp->getLHS())) {
                 RamValue* rhs = binRelOp->getRHS();
                 if (lhs->getLevel() == level && (isConstant(rhs) || getLevel(rhs) < level)) {
                     element = lhs->getElement();
                     return binRelOp->takeRHS();
                 }
             }
             if (auto* rhs = dynamic_cast<RamElementAccess*>(binRelOp->getRHS())) {
                 RamValue* lhs = binRelOp->getLHS();
                 if (rhs->getLevel() == level && (isConstant(lhs) || getLevel(lhs) < level)) {
                     element = rhs->getElement();
                     return binRelOp->takeLHS();
                 }
             }
         }
     }
     return std::unique_ptr<RamValue>(nullptr);
 }
std::vector<RamValue*> souffle::RamAggregate::getPattern () const inline
Get pattern.
Definition at line 446 of file RamOperation.h.
References pattern, and souffle::toPtrVector().
Referenced by souffle::Synthesiser::emitCode(), and souffle::Interpreter::evalOp().
{
         return toPtrVector(pattern);
     }
SearchColumns souffle::RamAggregate::getRangeQueryColumns () const inline
Get range query columns.
Definition at line 451 of file RamOperation.h.
References keys.
Referenced by souffle::Synthesiser::emitCode(), equal(), and souffle::Interpreter::evalOp().
{
         return keys;
     }
const RamRelationReference& souffle::RamAggregate::getRelation () const inline
Get relation.
Definition at line 441 of file RamOperation.h.
References relation.
Referenced by souffle::Synthesiser::emitCode(), equal(), and souffle::Interpreter::evalOp().
{
         return *relation;
     }
const RamValue* souffle::RamAggregate::getTargetExpression () const inline
Get target expression.
Definition at line 435 of file RamOperation.h.
References value.
Referenced by souffle::Synthesiser::emitCode(), equal(), and souffle::Interpreter::evalOp().
{
         assert(value);
         return value.get();
     }
void souffle::RamAggregate::print (std::ostream & os, int tabpos) const inline override virtual
Print.
Reimplemented from souffle::RamNestedOperation.
Definition at line 462 of file RamOperation.h.
References condition, COUNT, getCondition(), souffle::RamSearch::getIdentifier(), souffle::join(), MAX, MIN, pattern, souffle::RamNestedOperation::print(), relation, SUM, souffle::times(), and value.
{
         os << times('\t', tabpos);
         switch (function) {
             case MIN:
                 os << "MIN ";
                 break;
             case MAX:
                 os << "MAX ";
                 break;
             case COUNT:
                 os << "COUNT ";
                 break;
             case SUM:
                 os << "SUM ";
                 break;
         }
         if (function != COUNT) {
             os << *value << " ";
         }
         os << "AS t" << getIdentifier() << ".0 IN t" << getIdentifier() << "  " << relation->getName();
         os << "(" << join(pattern, ",", [&](std::ostream& out, const std::unique_ptr<RamValue>& value) {
             if (!value) {
                 out << "_";
             } else {
                 out << *value;
             }
         }) << ")";
         if (auto condition = getCondition()) {
             os << " WHERE ";
             condition->print(os);
         }
         os << " FOR \n";
         RamSearch::print(os, tabpos + 1);
     }
Field Documentation
std::unique_ptr<RamCondition> souffle::RamAggregate::condition private
Condition that is checked for each obtained tuple.
If condition is a nullptr, then no condition applies
Definition at line 399 of file RamOperation.h.
Referenced by addCondition(), apply(), getChildNodes(), getCondition(), and print().
Function souffle::RamAggregate::function private
Aggregation function.
Definition at line 402 of file RamOperation.h.
SearchColumns souffle::RamAggregate::keys = 0 private
Columns to be matched when using a range query.
Definition at line 415 of file RamOperation.h.
Referenced by addCondition(), clone(), and getRangeQueryColumns().
std::vector<std::unique_ptr<RamValue> > souffle::RamAggregate::pattern private
Pattern for filtering tuples.
Definition at line 412 of file RamOperation.h.
Referenced by addCondition(), apply(), clone(), equal(), getPattern(), and print().
std::unique_ptr<RamRelationReference> souffle::RamAggregate::relation private
Aggregation relation.
Definition at line 409 of file RamOperation.h.
Referenced by addCondition(), apply(), clone(), getRelation(), and print().
std::unique_ptr<RamValue> souffle::RamAggregate::value private
Aggregation value.
Definition at line 406 of file RamOperation.h.
Referenced by addCondition(), apply(), clone(), getTargetExpression(), and print().
The documentation for this class was generated from the following files:
RamOperation.h
RamOperation.cpp