souffle: souffle::EquivalenceRelation< TupleType >::iterator Class Reference
souffle::EquivalenceRelation< TupleType >::iterator Class Reference
#include <EquivalenceRelation.h>
Public Member Functions
iterator (const EquivalenceRelation *br, bool)
iterator (const EquivalenceRelation *br)
iterator (const EquivalenceRelation *br, const StatesBucket within)
iterator (const EquivalenceRelation *br, const value_type former, const StatesBucket within)
iterator (const EquivalenceRelation *br, const value_type former, value_type latter, const StatesBucket within)
iterator (const iterator &other)=default
iterator (iterator &&other)=default
bool operator!= (const iterator &other) const
const TupleType & operator* () const
iterator & operator++ ()
const TupleType * operator-> () const
iterator & operator= (const iterator &other)=default
bool operator== (const iterator &other) const
void setAnterior (const value_type a)
explicit set first half of cPair
void setPosterior (const value_type b)
explicit set second half of cPair
void updateAnterior ()
quick update to whatever the current index is pointing to
void updatePosterior ()
quick update to whatever the current index is pointing to
Private Types
enum IterType { ALL, ANTERIOR, ANTPOST, WITHIN }
Private Attributes
const EquivalenceRelation * br = nullptr
size_t cAnteriorIndex = 0
TupleType cPair
size_t cPosteriorIndex = 0
StatesBucket djSetList
StatesMap::iterator djSetMapListEnd
StatesMap::iterator djSetMapListIt
bool isEndVal = false
IterType ityp
Detailed Description
template<typename TupleType>
class souffle::EquivalenceRelation< TupleType >::iterator
Definition at line 263 of file EquivalenceRelation.h.
Member Enumeration Documentation
template<typename TupleType> enum souffle::EquivalenceRelation::iterator::IterType private
Enumerator
ALL
ANTERIOR
ANTPOST
WITHIN
Definition at line 269 of file EquivalenceRelation.h.
 { ALL, ANTERIOR, ANTPOST, WITHIN };
Constructor & Destructor Documentation
template<typename TupleType> souffle::EquivalenceRelation< TupleType >::iterator::iterator (const EquivalenceRelation * br, bool) inline explicit
Definition at line 286 of file EquivalenceRelation.h.
                 : br(br), isEndVal(true){};
template<typename TupleType> souffle::EquivalenceRelation< TupleType >::iterator::iterator (const EquivalenceRelation * br) inline explicit
Definition at line 289 of file EquivalenceRelation.h.
References souffle::EquivalenceRelation< TupleType >::iterator::djSetList, souffle::EquivalenceRelation< TupleType >::iterator::djSetMapListEnd, souffle::EquivalenceRelation< TupleType >::iterator::djSetMapListIt, souffle::EquivalenceRelation< TupleType >::iterator::isEndVal, souffle::PiggyList< T >::size(), souffle::EquivalenceRelation< TupleType >::iterator::updateAnterior(), and souffle::EquivalenceRelation< TupleType >::iterator::updatePosterior().
                 : br(br), ityp(IterType::ALL), djSetMapListIt(br->equivalencePartition.begin()),
                   djSetMapListEnd(br->equivalencePartition.end()) {
             // no need to fast forward if this iterator is empty
             if (djSetMapListIt == djSetMapListEnd) {
                 isEndVal = true;
                 return;
             }
             // grab the pointer to the list, and make it our current list
             djSetList = (*djSetMapListIt).second;
             assert(djSetList->size() != 0);
             updateAnterior();
             updatePosterior();
         }
template<typename TupleType> souffle::EquivalenceRelation< TupleType >::iterator::iterator (const EquivalenceRelation * br, const StatesBucket within) inline explicit
Definition at line 306 of file EquivalenceRelation.h.
References souffle::EquivalenceRelation< TupleType >::iterator::djSetList, souffle::EquivalenceRelation< TupleType >::iterator::isEndVal, souffle::PiggyList< T >::size(), souffle::EquivalenceRelation< TupleType >::iterator::updateAnterior(), and souffle::EquivalenceRelation< TupleType >::iterator::updatePosterior().
                 : br(br), ityp(IterType::WITHIN), djSetList(within) {
             // empty dj set
             if (djSetList->size() == 0) {
                 isEndVal = true;
             }
             updateAnterior();
             updatePosterior();
         }
template<typename TupleType> souffle::EquivalenceRelation< TupleType >::iterator::iterator (const EquivalenceRelation * br, const value_type former, const StatesBucket within) inline explicit
Definition at line 318 of file EquivalenceRelation.h.
References souffle::EquivalenceRelation< TupleType >::iterator::djSetList, souffle::EquivalenceRelation< TupleType >::iterator::isEndVal, souffle::EquivalenceRelation< TupleType >::iterator::setAnterior(), souffle::PiggyList< T >::size(), and souffle::EquivalenceRelation< TupleType >::iterator::updatePosterior().
                 : br(br), ityp(IterType::ANTERIOR), djSetList(within) {
             if (djSetList->size() == 0) {
                 isEndVal = true;
             }
             setAnterior(former);
             updatePosterior();
         }
template<typename TupleType> souffle::EquivalenceRelation< TupleType >::iterator::iterator (const EquivalenceRelation * br, const value_type former, value_type latter, const StatesBucket within) inline explicit
Definition at line 330 of file EquivalenceRelation.h.
References souffle::EquivalenceRelation< TupleType >::iterator::djSetList, souffle::EquivalenceRelation< TupleType >::iterator::isEndVal, souffle::EquivalenceRelation< TupleType >::iterator::setAnterior(), souffle::EquivalenceRelation< TupleType >::iterator::setPosterior(), and souffle::PiggyList< T >::size().
                 : br(br), ityp(IterType::ANTPOST), djSetList(within) {
             if (djSetList->size() == 0) {
                 isEndVal = true;
             }
             setAnterior(former);
             setPosterior(latter);
         }
template<typename TupleType> souffle::EquivalenceRelation< TupleType >::iterator::iterator (const iterator & other) default
template<typename TupleType> souffle::EquivalenceRelation< TupleType >::iterator::iterator (iterator && other) default
Member Function Documentation
template<typename TupleType> bool souffle::EquivalenceRelation< TupleType >::iterator::operator!= (const iterator & other) const inline
Definition at line 373 of file EquivalenceRelation.h.
{
             return !((*this) == other);
         }
template<typename TupleType> const TupleType& souffle::EquivalenceRelation< TupleType >::iterator::operator* () const inline
Definition at line 377 of file EquivalenceRelation.h.
References souffle::EquivalenceRelation< TupleType >::iterator::cPair.
{
             return cPair;
         }
template<typename TupleType> iterator& souffle::EquivalenceRelation< TupleType >::iterator::operator++ () inline
Definition at line 386 of file EquivalenceRelation.h.
References souffle::EquivalenceRelation< TupleType >::iterator::cAnteriorIndex, souffle::EquivalenceRelation< TupleType >::iterator::cPosteriorIndex, souffle::EquivalenceRelation< TupleType >::iterator::djSetList, souffle::EquivalenceRelation< TupleType >::iterator::djSetMapListEnd, souffle::EquivalenceRelation< TupleType >::iterator::djSetMapListIt, souffle::EquivalenceRelation< TupleType >::iterator::isEndVal, souffle::EquivalenceRelation< TupleType >::iterator::ityp, souffle::PiggyList< T >::size(), souffle::EquivalenceRelation< TupleType >::iterator::updateAnterior(), and souffle::EquivalenceRelation< TupleType >::iterator::updatePosterior().
{
             if (isEndVal) throw std::out_of_range("error: incrementing an out of range iterator");
             switch (ityp) {
                 case IterType::ALL:
                     // move posterior along one
                     // see if we can't move the posterior along
                     if (++cPosteriorIndex == djSetList->size()) {
                         // move anterior along one
                         // see if we can't move the anterior along one
                         if (++cAnteriorIndex == djSetList->size()) {
                             // move the djset it along one
                             // see if we can't move it along one (we're at the end)
                             if (++djSetMapListIt == djSetMapListEnd) {
                                 isEndVal = true;
                                 return *this;
                             }
                             // we can't iterate along this djset if it is empty
                             djSetList = (*djSetMapListIt).second;
                             if (djSetList->size() == 0)
                                 throw std::out_of_range("error: encountered a zero size djset");
                             // update our cAnterior and cPosterior
                             cAnteriorIndex = 0;
                             cPosteriorIndex = 0;
                             updateAnterior();
                             updatePosterior();
                         }
                         // we moved our anterior along one
                         updateAnterior();
                         cPosteriorIndex = 0;
                         updatePosterior();
                     }
                     // we just moved our posterior along one
                     updatePosterior();
                     break;
                 case IterType::ANTERIOR:
                     // step posterior along one, and if we can't, then we're done.
                     if (++cPosteriorIndex == djSetList->size()) {
                         isEndVal = true;
                         return *this;
                     }
                     updatePosterior();
                     break;
                 case IterType::ANTPOST:
                     // fixed anterior and posterior literally only points to one, so if we increment, its the
                     // end
                     isEndVal = true;
                     break;
                 case IterType::WITHIN:
                     // move posterior along one
                     // see if we can't move the posterior along
                     if (++cPosteriorIndex == djSetList->size()) {
                         // move anterior along one
                         // see if we can't move the anterior along one
                         if (++cAnteriorIndex == djSetList->size()) {
                             isEndVal = true;
                             return *this;
                         }
                         // we moved our anterior along one
                         updateAnterior();
                         cPosteriorIndex = 0;
                         updatePosterior();
                     }
                     // we just moved our posterior along one
                     updatePosterior();
                     break;
             }
             return *this;
         }
template<typename TupleType> const TupleType* souffle::EquivalenceRelation< TupleType >::iterator::operator-> () const inline
Definition at line 381 of file EquivalenceRelation.h.
References souffle::EquivalenceRelation< TupleType >::iterator::cPair.
{
             return &cPair;
         }
template<typename TupleType> iterator& souffle::EquivalenceRelation< TupleType >::iterator::operator= (const iterator & other) default
template<typename TupleType> bool souffle::EquivalenceRelation< TupleType >::iterator::operator== (const iterator & other) const inline
Definition at line 368 of file EquivalenceRelation.h.
References souffle::EquivalenceRelation< TupleType >::iterator::br, souffle::EquivalenceRelation< TupleType >::iterator::cPair, and souffle::EquivalenceRelation< TupleType >::iterator::isEndVal.
{
             if (isEndVal && other.isEndVal) return br == other.br;
             return isEndVal == other.isEndVal && cPair == other.cPair;
         }
template<typename TupleType> void souffle::EquivalenceRelation< TupleType >::iterator::setAnterior (const value_type a) inline
explicit set first half of cPair
Definition at line 342 of file EquivalenceRelation.h.
References souffle::EquivalenceRelation< TupleType >::iterator::cPair.
Referenced by souffle::EquivalenceRelation< TupleType >::iterator::iterator().
{
             this->cPair[0] = a;
         }
template<typename TupleType> void souffle::EquivalenceRelation< TupleType >::iterator::setPosterior (const value_type b) inline
explicit set second half of cPair
Definition at line 352 of file EquivalenceRelation.h.
References b, and souffle::EquivalenceRelation< TupleType >::iterator::cPair.
Referenced by souffle::EquivalenceRelation< TupleType >::iterator::iterator().
{
             this->cPair[1] = b;
         }
template<typename TupleType> void souffle::EquivalenceRelation< TupleType >::iterator::updateAnterior () inline
quick update to whatever the current index is pointing to
Definition at line 347 of file EquivalenceRelation.h.
References souffle::EquivalenceRelation< TupleType >::iterator::cAnteriorIndex, souffle::EquivalenceRelation< TupleType >::iterator::cPair, souffle::EquivalenceRelation< TupleType >::iterator::djSetList, and souffle::PiggyList< T >::get().
Referenced by souffle::EquivalenceRelation< TupleType >::iterator::iterator(), and souffle::EquivalenceRelation< TupleType >::iterator::operator++().
{
             this->cPair[0] = this->djSetList->get(this->cAnteriorIndex);
         }
template<typename TupleType> void souffle::EquivalenceRelation< TupleType >::iterator::updatePosterior () inline
quick update to whatever the current index is pointing to
Definition at line 357 of file EquivalenceRelation.h.
References souffle::EquivalenceRelation< TupleType >::iterator::cPair, souffle::EquivalenceRelation< TupleType >::iterator::cPosteriorIndex, souffle::EquivalenceRelation< TupleType >::iterator::djSetList, and souffle::PiggyList< T >::get().
Referenced by souffle::EquivalenceRelation< TupleType >::iterator::iterator(), and souffle::EquivalenceRelation< TupleType >::iterator::operator++().
{
             this->cPair[1] = this->djSetList->get(this->cPosteriorIndex);
         }
Field Documentation
template<typename TupleType> const EquivalenceRelation* souffle::EquivalenceRelation< TupleType >::iterator::br = nullptr private
Definition at line 264 of file EquivalenceRelation.h.
Referenced by souffle::EquivalenceRelation< TupleType >::iterator::operator==().
template<typename TupleType> size_t souffle::EquivalenceRelation< TupleType >::iterator::cAnteriorIndex = 0 private
Definition at line 280 of file EquivalenceRelation.h.
Referenced by souffle::EquivalenceRelation< TupleType >::iterator::operator++(), and souffle::EquivalenceRelation< TupleType >::iterator::updateAnterior().
template<typename TupleType> TupleType souffle::EquivalenceRelation< TupleType >::iterator::cPair private
Definition at line 272 of file EquivalenceRelation.h.
Referenced by souffle::EquivalenceRelation< TupleType >::iterator::operator*(), souffle::EquivalenceRelation< TupleType >::iterator::operator->(), souffle::EquivalenceRelation< TupleType >::iterator::operator==(), souffle::EquivalenceRelation< TupleType >::iterator::setAnterior(), souffle::EquivalenceRelation< TupleType >::iterator::setPosterior(), souffle::EquivalenceRelation< TupleType >::iterator::updateAnterior(), and souffle::EquivalenceRelation< TupleType >::iterator::updatePosterior().
template<typename TupleType> size_t souffle::EquivalenceRelation< TupleType >::iterator::cPosteriorIndex = 0 private
Definition at line 282 of file EquivalenceRelation.h.
Referenced by souffle::EquivalenceRelation< TupleType >::iterator::operator++(), and souffle::EquivalenceRelation< TupleType >::iterator::updatePosterior().
template<typename TupleType> StatesBucket souffle::EquivalenceRelation< TupleType >::iterator::djSetList private
Definition at line 275 of file EquivalenceRelation.h.
Referenced by souffle::EquivalenceRelation< TupleType >::iterator::iterator(), souffle::EquivalenceRelation< TupleType >::iterator::operator++(), souffle::EquivalenceRelation< TupleType >::iterator::updateAnterior(), and souffle::EquivalenceRelation< TupleType >::iterator::updatePosterior().
template<typename TupleType> StatesMap::iterator souffle::EquivalenceRelation< TupleType >::iterator::djSetMapListEnd private
Definition at line 277 of file EquivalenceRelation.h.
Referenced by souffle::EquivalenceRelation< TupleType >::iterator::iterator(), and souffle::EquivalenceRelation< TupleType >::iterator::operator++().
template<typename TupleType> StatesMap::iterator souffle::EquivalenceRelation< TupleType >::iterator::djSetMapListIt private
Definition at line 276 of file EquivalenceRelation.h.
Referenced by souffle::EquivalenceRelation< TupleType >::iterator::iterator(), and souffle::EquivalenceRelation< TupleType >::iterator::operator++().
template<typename TupleType> bool souffle::EquivalenceRelation< TupleType >::iterator::isEndVal = false private
Definition at line 266 of file EquivalenceRelation.h.
Referenced by souffle::EquivalenceRelation< TupleType >::iterator::iterator(), souffle::EquivalenceRelation< TupleType >::iterator::operator++(), and souffle::EquivalenceRelation< TupleType >::iterator::operator==().
template<typename TupleType> IterType souffle::EquivalenceRelation< TupleType >::iterator::ityp private
Definition at line 270 of file EquivalenceRelation.h.
Referenced by souffle::EquivalenceRelation< TupleType >::iterator::operator++().
The documentation for this class was generated from the following file:
EquivalenceRelation.h