souffle: souffle::RamIndexScan Class Reference
souffle::RamIndexScan Class Reference
Relation Scan with Index.
#include <RamOperation.h>
Public Member Functions
void apply (const RamNodeMapper &map) override
Apply mapper.
RamIndexScan * clone () const override
Create clone.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of child nodes.
std::vector< RamValue * > getRangePattern () const
Get range pattern.
const SearchColumns & getRangeQueryColumns () const
Get indexable columns of scan.
void print (std::ostream &os, int tabpos) const override
Print.
RamIndexScan (std::unique_ptr< RamRelationReference > r, size_t ident, std::vector< std::unique_ptr< RamValue >> queryPattern, SearchColumns keys, std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamRelationSearch
const RamRelationReference & getRelation () const
Get search relation.
bool isPureExistenceCheck () const
Check for pure existence check.
RamRelationSearch (RamNodeType type, std::unique_ptr< RamRelationReference > rel, size_t ident, std::unique_ptr< RamOperation > nested, std::string profileText="")
void setIsPureExistenceCheck (const bool isExistCheck)
Set as pure existence check.
Public Member Functions inherited from souffle::RamSearch
std::size_t getIdentifier () const
Get identifier.
const std::string & getProfileText () const
Get profile text.
RamSearch (RamNodeType type, size_t ident, std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamNestedOperation
RamOperation & getOperation () const
Get nested operation.
RamNestedOperation (RamNodeType type, std::unique_ptr< RamOperation > nested)
Public Member Functions inherited from souffle::RamOperation
void print (std::ostream &os) const override
Pretty print.
RamOperation (RamNodeType type)
Public Member Functions inherited from souffle::RamNode
RamNodeType getNodeType () const
Get type of node.
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
RamNode (RamNodeType type)
virtual ~RamNode ()=default
A virtual destructor for RAM nodes.
Protected Member Functions
bool equal (const RamNode &node) const override
Check equality.
Protected Attributes
SearchColumns keys = 0
Indexable columns for a range query.
std::vector< std::unique_ptr
< RamValue > > queryPattern
Values of index per column of table (if indexable)
Detailed Description
Relation Scan with Index.
Search for tuples of a relation matching a criteria
Definition at line 232 of file RamOperation.h.
Constructor & Destructor Documentation
souffle::RamIndexScan::RamIndexScan (std::unique_ptr< RamRelationReference > r, size_t ident, std::vector< std::unique_ptr< RamValue >> queryPattern, SearchColumns keys, std::unique_ptr< RamOperation > nested, std::string profileText = "") inline
Definition at line 241 of file RamOperation.h.
Referenced by clone().
             : RamRelationSearch(RN_IndexScan, std::move(r), ident, std::move(nested), std::move(profileText)),
               queryPattern(std::move(queryPattern)), keys(keys) {}
Member Function Documentation
void souffle::RamIndexScan::apply (const RamNodeMapper & map) inline override virtual
Apply mapper.
Reimplemented from souffle::RamRelationSearch.
Definition at line 308 of file RamOperation.h.
References souffle::RamRelationSearch::apply(), and queryPattern.
{
         RamRelationSearch::apply(map);
         for (auto& cur : queryPattern) {
             if (cur) {
                 cur = map(std::move(cur));
             }
         }
     }
RamIndexScan* souffle::RamIndexScan::clone () const inline override virtual
Create clone.
Implements souffle::RamOperation.
Definition at line 294 of file RamOperation.h.
References souffle::RamSearch::getIdentifier(), souffle::RamNestedOperation::getOperation(), souffle::RamSearch::getProfileText(), souffle::RamRelationSearch::getRelation(), keys, queryPattern, and RamIndexScan().
{
         std::vector<std::unique_ptr<RamValue>> resQueryPattern;
         for (auto& cur : queryPattern) {
             if (cur) {
                 resQueryPattern.push_back(std::unique_ptr<RamValue>(cur->clone()));
             }
         }
         RamIndexScan* res = new RamIndexScan(std::unique_ptr<RamRelationReference>(getRelation().clone()),
                 getIdentifier(), std::move(resQueryPattern), keys,
                 std::unique_ptr<RamOperation>(getOperation().clone()), getProfileText());
         return res;
     }
bool souffle::RamIndexScan::equal (const RamNode & node) const inline override protected virtual
Check equality.
Reimplemented from souffle::RamRelationSearch.
Definition at line 319 of file RamOperation.h.
References souffle::RamRelationSearch::equal(), souffle::equal_targets(), keys, and queryPattern.
{
         assert(nullptr != dynamic_cast<const RamIndexScan*>(&node));
         const auto& other = static_cast<const RamIndexScan&>(node);
         return RamRelationSearch::equal(other) && equal_targets(queryPattern, other.queryPattern) &&
                keys == other.keys;
     }
std::vector<const RamNode*> souffle::RamIndexScan::getChildNodes () const inline override virtual
Obtain list of child nodes.
Reimplemented from souffle::RamNestedOperation.
Definition at line 283 of file RamOperation.h.
References souffle::RamNestedOperation::getChildNodes(), and queryPattern.
{
         auto res = RamRelationSearch::getChildNodes();
         for (auto& cur : queryPattern) {
             if (cur) {
                 res.push_back(cur.get());
             }
         }
         return res;
     }
std::vector<RamValue*> souffle::RamIndexScan::getRangePattern () const inline
Get range pattern.
Definition at line 248 of file RamOperation.h.
References queryPattern, and souffle::toPtrVector().
Referenced by souffle::Synthesiser::emitCode(), and souffle::Interpreter::evalOp().
{
         return toPtrVector(queryPattern);
     }
const SearchColumns& souffle::RamIndexScan::getRangeQueryColumns () const inline
Get indexable columns of scan.
Definition at line 253 of file RamOperation.h.
References keys.
Referenced by souffle::Synthesiser::emitCode(), and souffle::Interpreter::evalOp().
{
         return keys;
     }
void souffle::RamIndexScan::print (std::ostream & os, int tabpos) const inline override virtual
Print.
Reimplemented from souffle::RamNestedOperation.
Definition at line 258 of file RamOperation.h.
References souffle::RamRelationReference::getArg(), souffle::RamRelationReference::getArity(), souffle::RamSearch::getIdentifier(), souffle::RamRelationReference::getName(), souffle::RamRelationSearch::getRelation(), i, souffle::RamRelationSearch::isPureExistenceCheck(), souffle::RamNestedOperation::print(), queryPattern, and souffle::times().
{
         const RamRelationReference& rel = getRelation();
         os << times('\t', tabpos);
         if (isPureExistenceCheck()) {
             os << "if  t" << getIdentifier() << "  " << getRelation().getName() << " WITH ";
         } else {
             os << "SEARCH " << rel.getName() << " AS t" << getIdentifier() << " ON INDEX ";
         }
         bool first = true;
         for (unsigned int i = 0; i < rel.getArity(); ++i) {
             if (queryPattern[i] != nullptr) {
                 if (first) {
                     first = false;
                 } else {
                     os << " and ";
                 }
                 os << "t" << getIdentifier() << "." << rel.getArg(i) << "=";
                 queryPattern[i]->print(os);
             }
         }
         os << '\n';
         RamRelationSearch::print(os, tabpos + 1);
     }
Field Documentation
SearchColumns souffle::RamIndexScan::keys = 0 protected
Indexable columns for a range query.
Definition at line 238 of file RamOperation.h.
Referenced by clone(), equal(), and getRangeQueryColumns().
std::vector<std::unique_ptr<RamValue> > souffle::RamIndexScan::queryPattern protected
Values of index per column of table (if indexable)
Definition at line 235 of file RamOperation.h.
Referenced by apply(), clone(), equal(), getChildNodes(), getRangePattern(), and print().
The documentation for this class was generated from the following file:
RamOperation.h