souffle: souffle::RamValueLevelAnalysis Class Reference
souffle::RamValueLevelAnalysis Class Reference
#include <RamValueLevel.h>
Public Member Functions
size_t getLevel (const RamValue *value) const
Get level.
void run (const RamTranslationUnit &translationUnit) override
run level analysis for a RAM translation unit
Public Member Functions inherited from souffle::RamAnalysis
virtual void print (std::ostream &os) const
print the analysis result in HTML format
virtual ~RamAnalysis ()=default
Static Public Attributes
static constexpr const char * name = "value-level-analysis"
name of analysis
Detailed Description
Definition at line 27 of file RamValueLevel.h.
Member Function Documentation
size_t souffle::RamValueLevelAnalysis::getLevel (const RamValue * value) const
Get level.
Get level of value (which for-loop of a query)
Definition at line 23 of file RamValueLevel.cpp.
References souffle::RamIntrinsicOperator::getArguments(), souffle::RamUserDefinedOperator::getArguments(), souffle::RamPack::getArguments(), souffle::RamElementAccess::getLevel(), and souffle::pack().
Referenced by souffle::CreateIndicesTransformer::getIndexElement(), and souffle::RamConditionLevelAnalysis::getLevel().
{
     // visitor
     class ValueLevelVisitor : public RamVisitor<size_t> {
     public:
         // number
         size_t visitNumber(const RamNumber& num) override {
             return 0;
         }
         // tuple element access
         size_t visitElementAccess(const RamElementAccess& elem) override {
             return elem.getLevel();
         }
         // auto increment
         size_t visitAutoIncrement(const RamAutoIncrement& increment) override {
             return 0;
         }
         // intrinsic functors
         size_t visitIntrinsicOperator(const RamIntrinsicOperator& op) override {
             size_t level = 0;
             for (const auto& arg : op.getArguments()) {
                 if (arg != nullptr) {
                     level = std::max(level, visit(arg));
                 }
             }
             return level;
         }
         // pack operator
         size_t visitPack(const RamPack& pack) override {
             size_t level = 0;
             for (const auto& arg : pack.getArguments()) {
                 if (arg) {
                     level = std::max(level, visit(arg));
                 }
             }
             return level;
         }
         // argument
         size_t visitArgument(const RamArgument& arg) override {
             return 0;
         }
         // user defined operator
         size_t visitUserDefinedOperator(const RamUserDefinedOperator& op) override {
             size_t level = 0;
             for (const auto& arg : op.getArguments()) {
                 if (arg != nullptr) {
                     level = std::max(level, visit(arg));
                 }
             }
             return level;
         }
     };
     return ValueLevelVisitor().visit(value);
 }
void souffle::RamValueLevelAnalysis::run (const RamTranslationUnit & translationUnit) inline override virtual
run level analysis for a RAM translation unit
Implements souffle::RamAnalysis.
Definition at line 33 of file RamValueLevel.h.
 {}
Field Documentation
constexpr const char* souffle::RamValueLevelAnalysis::name = "value-level-analysis" static
name of analysis
Definition at line 30 of file RamValueLevel.h.
The documentation for this class was generated from the following files:
RamValueLevel.h
RamValueLevel.cpp